<!doctype html><html><head><meta charset="utf-8"><title>Rejected Items Report</title><style>
@page{margin:18mm}body{font-family:'DejaVu Sans',sans-serif;color:#172033;font-size:11px}h1{color:#991b1b;margin:0}.header{border-bottom:3px solid #dc2626;padding-bottom:12px}.meta{width:100%;margin:18px 0;border-collapse:collapse}.meta td{width:50%;padding:7px;border:1px solid #dbe3ee}.label{display:block;color:#64748b;font-size:9px;text-transform:uppercase}.section{margin-top:18px}.evidence-grid{width:100%;border-collapse:separate;border-spacing:8px}.evidence-cell{width:50%;vertical-align:top;border:1px solid #dbe3ee;padding:8px}.evidence-image{display:block;max-width:260px;max-height:200px;margin:0 auto 7px}.evidence-name{font-weight:bold;overflow-wrap:anywhere}.evidence-size{color:#64748b;font-size:9px}.unavailable{height:90px;background:#f8fafc;color:#64748b;text-align:center;line-height:90px}.notice{margin-top:24px;padding:12px;background:#fef2f2;border:1px solid #fecaca}.footer{margin-top:32px;color:#64748b;font-size:9px}
</style></head><body>
@php($item = $case->inspectionItem)
@php($inspection = $item->inspection)
@php($receiving = $inspection->receiving)
@php($po = $receiving->purchaseOrder)
<div class="header"><h1>Rejected Items Report</h1><div>Case {{ sprintf('RJ-%06d', $case->id) }}</div></div>
<table class="meta"><tr><td><span class="label">Supplier</span>{{ $supplier->name }} ({{ $supplier->supplier_code }})</td><td><span class="label">Purchase Order</span>{{ $po->po_number }}</td></tr><tr><td><span class="label">Receiving</span>{{ $receiving->receiving_no }}</td><td><span class="label">Inspection date</span>{{ $inspection->completed_at?->format('M d, Y g:i A') }}</td></tr><tr><td><span class="label">Product</span>{{ $item->receivingItem->product_name }}</td><td><span class="label">Unit</span>{{ $item->receivingItem->unit }}</td></tr><tr><td><span class="label">Delivered / Accepted</span>{{ number_format($item->receivingItem->delivered_quantity) }} / {{ number_format($item->accepted_quantity) }}</td><td><span class="label">Rejected quantity</span>{{ number_format($item->rejected_quantity) }}</td></tr><tr><td colspan="2"><span class="label">QA result</span>{{ $item->inspection_result }}</td></tr></table>
<div class="section"><strong>QA findings</strong><p>{{ $item->remarks ?: 'No additional remarks were recorded.' }}</p></div>
<div class="section"><strong>Evidence</strong>
@if(count($evidence) === 0)<p>No evidence files recorded.</p>@else
<table class="evidence-grid">
@foreach(array_chunk($evidence, 2) as $row)<tr>
@foreach($row as $index => $attachment)<td class="evidence-cell"><span class="label">Evidence {{ ($loop->parent->index * 2) + $loop->iteration }}</span>
@if($attachment['kind'] === 'image')<img class="evidence-image" src="{{ $attachment['data_uri'] }}" alt="Evidence image">
@elseif($attachment['kind'] === 'pdf')<div class="unavailable">PDF Evidence</div>
@else<div class="unavailable">Evidence unavailable</div>@endif
<div class="evidence-name">{{ $attachment['original_name'] }}</div>
@if($attachment['file_size'])<div class="evidence-size">{{ number_format($attachment['file_size'] / 1048576, 2) }} MB</div>@endif
</td>@endforeach
@if(count($row) === 1)<td class="evidence-cell" style="border:0"></td>@endif
</tr>@endforeach
</table>@endif</div>
<div class="notice">Please contact Archon Nell Incorporated to coordinate return, replacement, or corrective action.</div>
<div class="footer">Generated by SmartChain · Sent {{ now()->format('M d, Y g:i A') }}. Evidence is retained securely in the system and is not exposed through storage paths.</div>
</body></html>
