import { useCallback, useEffect, useState, type FormEvent, type ReactNode } from 'react';
import { AlertCircle, CheckCircle, ChevronLeft, ChevronRight, DollarSign, Edit, Eye, Grid, Package, PackageX, Plus, Search, Table, Trash2, X, XCircle } from 'lucide-react';
import { apiClient } from '../../lib/api';

type Status = 'IN STOCK' | 'LOW STOCK' | 'OUT OF STOCK';
type Product = { id:number; name:string; category:string|null; brand:string|null; supplier:string|null; warehouses:string[]; current_stock:number; unit:string|null; cost_price:number|null; selling_price:number|null; reorder_level:number|null; status:Status|null; inventory_value:number|null; created_at:string; updated_at:string };
type ProductForm = Pick<Product, 'name'|'category'|'brand'|'unit'|'cost_price'|'selling_price'|'reorder_level'>;
type CatalogResponse = { data:Product[]; meta?:{current_page:number;per_page:number;total:number;last_page:number}; current_page?:number; per_page?:number; total?:number; last_page?:number; summary?:{total_products:number;low_stock_items:number;out_of_stock:number;total_inventory_value:number|null}; filters?:{categories:string[];brands:string[];suppliers:string[];warehouses:{id:number;name:string}[];statuses:Status[]} };
const emptyForm:ProductForm = { name:'', category:'', brand:'', unit:null, cost_price:null, selling_price:null, reorder_level:null };
const money = (value:number|null) => value === null ? '—' : new Intl.NumberFormat('en-PH',{style:'currency',currency:'PHP'}).format(value);
const warehouseNames = (value:unknown):string[] => Array.isArray(value)
  ? value.map((warehouse) => typeof warehouse === 'string' ? warehouse : (warehouse && typeof warehouse === 'object' && 'name' in warehouse ? String(warehouse.name) : '')).filter(Boolean)
  : [];
const warehouseLabel = (value:unknown, fallback='—') => warehouseNames(value).join(', ') || fallback;
const numberValue = (value:unknown) => { const number=Number(value); return Number.isFinite(number)?number:0; };
const optionalNumber = (value:unknown):number|null => value == null || value === '' ? null : (Number.isFinite(Number(value)) ? Number(value) : null);
const normalizeProduct = (value:unknown):Product => {
  const product=(value&&typeof value==='object'?value:{}) as Record<string,unknown>;
  const relatedName=(field:unknown) => typeof field==='string'?field:(field&&typeof field==='object'&&'name' in field?String(field.name):null);
  return {
    id:numberValue(product.id), name:String(product.name??''), category:relatedName(product.category), brand:relatedName(product.brand), supplier:relatedName(product.supplier),
    warehouses:warehouseNames(product.warehouses??product.warehouse), current_stock:numberValue(product.current_stock??product.stock??product.quantity), unit:product.unit == null ? null : String(product.unit),
    cost_price:optionalNumber(product.cost_price), selling_price:optionalNumber(product.selling_price), reorder_level:optionalNumber(product.reorder_level),
    status:(['IN STOCK','LOW STOCK','OUT OF STOCK'].includes(String(product.status))?String(product.status):null) as Status|null,
    inventory_value:optionalNumber(product.inventory_value), created_at:String(product.created_at??''), updated_at:String(product.updated_at??''),
  };
};

const StatusBadge = ({status}:{status:Status|null}) => {
  if (status === null) return <span title="Reorder level has not been provided">—</span>;
  const style = status === 'IN STOCK' ? 'text-green-600 dark:text-emerald-400 bg-transparent dark:bg-emerald-500/10 border-emerald-200 dark:border-emerald-500/20' : status === 'LOW STOCK' ? 'text-yellow-600 dark:text-yellow-400 bg-transparent dark:bg-yellow-500/10 border-amber-200 dark:border-yellow-500/20' : 'text-red-600 dark:text-red-400 bg-transparent dark:bg-red-500/10 border-red-200 dark:border-red-500/20';
  const Icon = status === 'IN STOCK' ? CheckCircle : status === 'LOW STOCK' ? AlertCircle : XCircle;
  return <span className={`inline-flex items-center gap-1.5 px-2.5 py-1 rounded-full text-xs font-medium dark:font-normal border ${style}`}><Icon className="w-3 h-3"/>{status}</span>;
};
const Kpi = ({label,value,icon}:{label:string;value:string|number;icon:ReactNode}) => <div className="bg-[#0d1322] border border-gray-800/50 rounded-2xl p-5"><div className="flex justify-between"><div><p className="text-slate-400 text-xs uppercase tracking-wider">{label}</p><p className="text-2xl font-bold text-white mt-1.5">{value}</p></div><div className="p-2.5 bg-slate-800/60 rounded-lg">{icon}</div></div></div>;
const Field = ({label,children}:{label:string;children:ReactNode}) => <label className="block text-sm text-slate-400"><span className="block mb-2">{label}</span>{children}</label>;

function ProductModal({product,onClose,onSaved}:{product:Product|null;onClose:()=>void;onSaved:()=>void}) {
  const [form,setForm] = useState<ProductForm>(product ? {name:product.name,category:product.category??'',brand:product.brand??'',unit:product.unit,cost_price:product.cost_price,selling_price:product.selling_price,reorder_level:product.reorder_level} : emptyForm);
  const [saving,setSaving] = useState(false); const [error,setError] = useState('');
  const set = (key:keyof ProductForm,value:string|number|null) => setForm(old=>({...old,[key]:value}));
  const submit = async(e:FormEvent) => { e.preventDefault(); setSaving(true); setError(''); try { if(product) await apiClient.put(`/admin/products/${product.id}`,form); else await apiClient.post('/admin/products',form); onSaved(); } catch(cause:any) { const errors=cause.response?.data?.errors; setError(errors?Object.values(errors).flat().join(' '):cause.response?.data?.message??'Unable to save product.'); } finally { setSaving(false); } };
  return <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/60 backdrop-blur-sm p-4" onClick={onClose}><div className="bg-[#0d1322] border border-slate-800 rounded-2xl w-full max-w-2xl p-6" onClick={e=>e.stopPropagation()}><div className="flex justify-between mb-6"><h2 className="text-xl font-bold">{product?'Edit Product':'Add Product'}</h2><button onClick={onClose}><X/></button></div><form onSubmit={submit} className="space-y-4">{error&&<p className="text-red-400 bg-red-500/10 rounded-xl p-3">{error}</p>}<div className="grid grid-cols-1 md:grid-cols-2 gap-4">
    <Field label="Product Name *"><input required value={form.name} onChange={e=>set('name',e.target.value)} className="catalog-input"/></Field><Field label="Unit"><input value={form.unit??''} onChange={e=>set('unit',e.target.value || null)} className="catalog-input"/></Field>
    <Field label="Category"><input value={form.category??''} onChange={e=>set('category',e.target.value)} className="catalog-input"/></Field><Field label="Brand"><input value={form.brand??''} onChange={e=>set('brand',e.target.value)} className="catalog-input"/></Field>
    <Field label="Cost Price"><input type="number" min="0" step=".01" value={form.cost_price??''} onChange={e=>set('cost_price',e.target.value === '' ? null : Number(e.target.value))} className="catalog-input"/></Field><Field label="Selling Price"><input type="number" min="0" step=".01" value={form.selling_price??''} onChange={e=>set('selling_price',e.target.value === '' ? null : Number(e.target.value))} className="catalog-input"/></Field>
    <Field label="Reorder Level"><input type="number" min="0" value={form.reorder_level??''} onChange={e=>set('reorder_level',e.target.value === '' ? null : Number(e.target.value))} className="catalog-input"/></Field></div><p className="text-xs text-slate-500">Stock and warehouse assignments are managed by Inventory.</p><div className="flex justify-end gap-3 pt-4 border-t border-slate-800"><button type="button" onClick={onClose} className="px-4 py-2">Cancel</button><button disabled={saving} className="px-4 py-2 rounded-xl bg-slate-900 text-white hover:bg-slate-800 dark:bg-cyan-500 dark:hover:bg-cyan-400 dark:text-slate-950 disabled:opacity-50">{saving?'Saving…':'Save Product'}</button></div></form></div></div>;
}
const Select = ({value,onChange,label,options}:{value:string;onChange:(v:string)=>void;label:string;options:{value:string;label:string}[]}) => <select value={value} onChange={e=>onChange(e.target.value)} className="h-11 min-w-40 flex-1 bg-white dark:bg-[#101929] border border-slate-300 dark:border-slate-800 rounded-xl px-3 text-sm text-slate-700 dark:text-slate-300 focus:outline-none focus:border-cyan-500 focus:ring-2 focus:ring-cyan-500/10"><option value="">{label}</option>{options.map(o=><option key={o.value} value={o.value}>{o.label}</option>)}</select>;

export default function ProductCatalog() {
  const [response,setResponse]=useState<CatalogResponse|null>(null); const [search,setSearch]=useState(''); const [category,setCategory]=useState(''); const [brand,setBrand]=useState(''); const [warehouse,setWarehouse]=useState(''); const [status,setStatus]=useState(''); const [page,setPage]=useState(1); const [view,setView]=useState<'table'|'grid'>('table'); const [modal,setModal]=useState<Product|null|undefined>(); const [details,setDetails]=useState<Product|null>(null); const [error,setError]=useState(''); const [loading,setLoading]=useState(true);
  const load=useCallback(async()=>{setLoading(true);setError('');try{const {data}=await apiClient.get<CatalogResponse>('/admin/products',{params:{search:search||undefined,category:category||undefined,brand:brand||undefined,warehouse_id:warehouse||undefined,status:status||undefined,page,per_page:10}});const products=(Array.isArray(data?.data)?data.data:[]).map(normalizeProduct);const meta=data?.meta??{current_page:data?.current_page??1,per_page:data?.per_page??10,total:data?.total??products.length,last_page:data?.last_page??1};setResponse({...data,data:products,meta});}catch(cause:any){setResponse(null);setError(cause.response?.data?.message??'Unable to load products.');}finally{setLoading(false);}},[search,category,brand,warehouse,status,page]);
  useEffect(()=>{const timer=setTimeout(load,250);return()=>clearTimeout(timer)},[load]); useEffect(()=>setPage(1),[search,category,brand,warehouse,status]);
  const remove=async(product:Product)=>{if(!confirm(`Delete ${product.name}? Referenced products will be protected.`))return;try{await apiClient.delete(`/admin/products/${product.id}`);await load()}catch(cause:any){setError(cause.response?.data?.message??'Unable to delete product.')}};
  const summary={total_products:numberValue(response?.summary?.total_products??response?.total),low_stock_items:numberValue(response?.summary?.low_stock_items),out_of_stock:numberValue(response?.summary?.out_of_stock),total_inventory_value:optionalNumber(response?.summary?.total_inventory_value)}; const filters=response?.filters??{categories:[],brands:[],suppliers:[],warehouses:[],statuses:[]}; const pagination=response?.meta??{current_page:response?.current_page??1,per_page:response?.per_page??10,total:response?.total??0,last_page:response?.last_page??1};
  return <div className="p-6 space-y-6 text-slate-900 dark:text-slate-100"><style>{`.catalog-input{width:100%;height:2.75rem;background:#fff;border:1px solid #cbd5e1;border-radius:.75rem;padding:.625rem .75rem;color:#0f172a;outline:none}.catalog-input.catalog-search{padding-left:2.25rem}.catalog-input::placeholder{color:#94a3b8}.dark .catalog-input{background:#0f172a;border-color:#334155;color:white}.catalog-input:focus{border-color:#06b6d4;box-shadow:0 0 0 2px rgba(6,182,212,.1)}`}</style>
    <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4"><div><h1 className="text-2xl font-bold">Product Catalog</h1><p className="text-slate-400 text-sm mt-1">Manage product master data</p></div><button onClick={()=>setModal(null)} className="inline-flex h-11 items-center justify-center gap-2 bg-slate-900 hover:bg-slate-800 text-white dark:bg-cyan-500 dark:hover:bg-cyan-400 dark:text-slate-950 px-4 rounded-xl font-medium shadow-sm focus:outline-none focus:ring-2 focus:ring-cyan-500/30 transition-opacity"><Plus className="w-4 h-4"/>Add Product</button></div>
    <div className="grid grid-cols-1 sm:grid-cols-2 xl:grid-cols-4 gap-4"><Kpi label="Total Products" value={summary.total_products} icon={<Package className="text-cyan-400"/>}/><Kpi label="Low Stock Items" value={summary.low_stock_items} icon={<AlertCircle className="text-yellow-400"/>}/><Kpi label="Out of Stock" value={summary.out_of_stock} icon={<PackageX className="text-red-400"/>}/><Kpi label="Total Inventory Value" value={money(summary.total_inventory_value)} icon={<DollarSign className="text-emerald-400"/>}/></div>
    {error&&<div className="bg-red-500/10 border border-red-500/20 text-red-300 rounded-xl p-3">{error}</div>}
    <div className="flex flex-wrap gap-3 rounded-2xl border border-slate-200 dark:border-slate-800 bg-white dark:bg-[#0d1322] p-3 shadow-sm dark:shadow-none"><div className="relative min-w-64 flex-[2_1_20rem]"><Search className="pointer-events-none absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-slate-400 dark:text-slate-500"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search product name, category, or brand" className="catalog-input catalog-search"/></div><Select value={category} onChange={setCategory} label="All Categories" options={filters.categories.map(v=>({value:v,label:v}))}/><Select value={brand} onChange={setBrand} label="All Brands" options={filters.brands.map(v=>({value:v,label:v}))}/><Select value={warehouse} onChange={setWarehouse} label="All Warehouses" options={filters.warehouses.map(v=>({value:String(v.id),label:v.name}))}/><Select value={status} onChange={setStatus} label="All Status" options={filters.statuses.map(v=>({value:v,label:v}))}/><button onClick={()=>{setSearch('');setCategory('');setBrand('');setWarehouse('');setStatus('')}} className="h-11 px-4 bg-white dark:bg-transparent border border-slate-300 dark:border-slate-700 text-slate-700 dark:text-slate-300 hover:bg-slate-50 dark:hover:bg-slate-800 hover:border-slate-400 dark:hover:border-slate-600 rounded-xl focus:outline-none focus:ring-2 focus:ring-cyan-500/10 transition-colors">Reset</button></div>
    <div className="bg-[#0d1322] border border-slate-800 rounded-2xl overflow-hidden"><div className="flex justify-between px-5 py-3 border-b border-slate-800"><span className="text-sm text-slate-400">{pagination?.total??0} products</span><div className="flex bg-slate-800/50 rounded-lg p-1"><button onClick={()=>setView('table')} className={`p-1.5 rounded ${view==='table'?'bg-slate-900 text-white dark:bg-cyan-500 dark:text-slate-950':''}`}><Table className="w-4 h-4"/></button><button onClick={()=>setView('grid')} className={`p-1.5 rounded ${view==='grid'?'bg-slate-900 text-white dark:bg-cyan-500 dark:text-slate-950':''}`}><Grid className="w-4 h-4"/></button></div></div>
      {loading?<div className="p-10 text-center text-slate-400">Loading products…</div>:view==='table'?<ProductTable products={response?.data??[]} onView={setDetails} onEdit={setModal} onDelete={remove}/>:<ProductGrid products={response?.data??[]} onView={setDetails} onEdit={setModal}/>}<div className="flex justify-between px-5 py-4 border-t border-slate-800"><span className="text-sm text-slate-400">Page {pagination?.current_page??1} of {pagination?.last_page??1}</span><div className="flex gap-2"><button disabled={page<=1} onClick={()=>setPage(p=>p-1)} className="p-2 border rounded-lg disabled:opacity-40"><ChevronLeft className="w-4 h-4"/></button><button disabled={page>=(pagination?.last_page??1)} onClick={()=>setPage(p=>p+1)} className="p-2 border rounded-lg disabled:opacity-40"><ChevronRight className="w-4 h-4"/></button></div></div></div>
    {modal!==undefined&&<ProductModal product={modal} onClose={()=>setModal(undefined)} onSaved={()=>{setModal(undefined);void load()}}/>}{details&&<Details product={details} onClose={()=>setDetails(null)}/>}</div>;
}

const ProductTable=({products,onView,onEdit,onDelete}:{products:Product[];onView:(p:Product)=>void;onEdit:(p:Product)=>void;onDelete:(p:Product)=>void})=><div className="overflow-x-auto w-full custom-scrollbar"><table className="w-full min-w-max text-sm"><thead className="bg-[#0b0f19]/50 text-xs uppercase text-slate-400"><tr>{['Product Name','Category','Brand','Supplier','Warehouse','Current Stock','Unit','Cost Price','Selling Price','Reorder Level','Status','Actions'].map(v=><th key={v} className="px-4 py-3 text-left whitespace-nowrap">{v}</th>)}</tr></thead><tbody>{products.map(p=><tr key={p.id} className="border-t border-slate-800"><td className="px-4 py-3 font-medium text-white whitespace-nowrap">{p.name}</td><td className="px-4 py-3 whitespace-nowrap">{p.category||'—'}</td><td className="px-4 py-3 whitespace-nowrap">{p.brand||'—'}</td><td className="px-4 py-3 whitespace-nowrap">{p.supplier||'—'}</td><td className="px-4 py-3 whitespace-nowrap">{warehouseLabel(p.warehouses)}</td><td className="px-4 py-3 text-center whitespace-nowrap">{p.current_stock}</td><td className="px-4 py-3 whitespace-nowrap">{p.unit??'—'}</td><td className="px-4 py-3 text-right whitespace-nowrap">{money(p.cost_price)}</td><td className="px-4 py-3 text-right whitespace-nowrap">{money(p.selling_price)}</td><td className="px-4 py-3 text-right whitespace-nowrap">{p.reorder_level??'—'}</td><td className="px-4 py-3 whitespace-nowrap"><StatusBadge status={p.status}/></td><td className="px-4 py-3 whitespace-nowrap"><div className="flex"><button onClick={()=>onView(p)} className="p-2"><Eye className="w-4 h-4"/></button><button onClick={()=>onEdit(p)} className="p-2"><Edit className="w-4 h-4"/></button><button onClick={()=>onDelete(p)} className="p-2 text-red-400"><Trash2 className="w-4 h-4"/></button></div></td></tr>)}{!products.length&&<tr><td colSpan={12} className="p-10 text-center text-slate-400 whitespace-nowrap">No products found.</td></tr>}</tbody></table></div>;
const ProductGrid=({products,onView,onEdit}:{products:Product[];onView:(p:Product)=>void;onEdit:(p:Product)=>void})=><div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-4 gap-4 p-5">{products.map(p=><div key={p.id} className="bg-white dark:bg-transparent border border-slate-200 dark:border-slate-800 hover:border-slate-300 dark:hover:border-slate-700 shadow-sm dark:shadow-none rounded-2xl p-5 transition-colors"><h3 className="font-semibold text-slate-900 dark:text-white">{p.name}</h3><p className="text-sm text-slate-500 dark:text-slate-400">{p.category||'Uncategorized'} · {p.brand||'No brand'}</p><div className="my-4 p-3 bg-slate-50 dark:bg-slate-950/50 border border-slate-200 dark:border-slate-800 rounded-xl"><p className="text-sm font-medium text-slate-500 dark:text-slate-400">Available stock</p><p className="text-xl font-bold text-slate-900 dark:text-white">{p.current_stock} {p.unit??'—'}</p><p className="text-sm text-slate-600 dark:text-slate-500">{warehouseLabel(p.warehouses,'No warehouse inventory')}</p></div><div className="flex justify-between"><StatusBadge status={p.status}/><span className="font-semibold text-cyan-600 dark:text-cyan-400">{money(p.inventory_value)}</span></div><div className="flex justify-end gap-3 mt-4"><button onClick={()=>onView(p)} className="p-1.5 text-slate-600 dark:text-slate-400 hover:text-slate-900 dark:hover:text-white transition-colors"><Eye className="w-4 h-4"/></button><button onClick={()=>onEdit(p)} className="p-1.5 text-slate-600 dark:text-slate-400 hover:text-slate-900 dark:hover:text-white transition-colors"><Edit className="w-4 h-4"/></button></div></div>)}</div>;
const Details=({product:p,onClose}:{product:Product;onClose:()=>void})=><div className="fixed inset-0 z-50 bg-black/60 flex justify-end" onClick={onClose}><div className="w-full max-w-md bg-white dark:bg-[#0d1322] text-slate-900 dark:text-slate-100 p-6" onClick={e=>e.stopPropagation()}><div className="flex justify-between"><h2 className="text-xl font-bold text-slate-900 dark:text-white">{p.name}</h2><button onClick={onClose} className="text-slate-500 dark:text-slate-400 hover:text-slate-900 dark:hover:text-white"><X/></button></div><div className="mt-6 space-y-4">{[['Category',p.category||'—'],['Brand',p.brand||'—'],['Warehouses',warehouseLabel(p.warehouses)],['Current Stock',`${p.current_stock} ${p.unit??'—'}`],['Cost Price',money(p.cost_price)],['Selling Price',money(p.selling_price)],['Reorder Level',p.reorder_level === null ? '—' : String(p.reorder_level)],['Inventory Value',money(p.inventory_value)]].map(([a,b])=><div key={a} className="flex justify-between border-b border-slate-300 dark:border-slate-800 pb-3"><span className="text-slate-600 dark:text-slate-400">{a}</span><span className="text-slate-900 dark:text-slate-100">{b}</span></div>)}<StatusBadge status={p.status}/></div></div></div>;
