import { useCallback, useEffect, useMemo, useState } from 'react';
import { AlertTriangle, Archive, CheckCircle2, Eye, LayoutGrid, LayoutList, Loader2, PackageCheck, RefreshCw, Search, Send, X } from 'lucide-react';
import { apiClient } from '../../lib/api';
import { EvidenceGallery, type QaAttachment } from '../QA/components/EvidenceGallery';

type CaseStatus = 'PENDING_REVIEW' | 'SENDING' | 'SENT' | 'FAILED' | 'REPLACEMENT_PENDING' | 'RESOLVED';
type Disposition = 'REPLACEMENT' | 'NO_REPLACEMENT';
interface RejectionCase {
  id: number; reference: string; status: CaseStatus; product: string; unit: string | null;
  delivered_quantity: number; accepted_quantity: number; rejected_quantity: number; reason: string | null; inspection_result: string; inspection_date: string;
  inspected_by: string | null; receiving: { id: number; number: string; delivery_date: string; reference_number: string | null; replacement_for_reference: string | null }; purchase_order: { id: number; number: string } | null;
  registered_supplier: { code: string; name: string; email: string | null } | null;
  supplier: { id: number | null; code: string | null; name: string; email: string | null }; supplier_error: string | null;
  can_send: boolean; send_block_reason: string | null; resend_available_at: string | null;
  original_supplier_name: string;
  attachments: QaAttachment[]; send_attempts: number; sent_at: string | null; sent_by: string | null;
  last_error_at: string | null; last_error: string | null; resolved_at: string | null;
  resolved_by: string | null; resolution_notes: string | null;
  resolution_type: 'REPLACEMENT' | 'NO_REPLACEMENT' | 'REPLACEMENT_RECEIVED' | null;
  routed_to_receiving_at: string | null; routed_by: string | null;
  replacement_receiving: { id: number; number: string; status: string; expected_quantity: number; qa_completed: boolean } | null;
  can_route_to_receiving: boolean; can_close: boolean; can_resolve: boolean; resolve_block_reason: string | null;
}

const labels: Record<CaseStatus, string> = { PENDING_REVIEW: 'Pending review', SENDING: 'Sending', SENT: 'Sent', FAILED: 'Failed', REPLACEMENT_PENDING: 'Replacement pending', RESOLVED: 'Resolved' };
const resolutionLabels: Record<NonNullable<RejectionCase['resolution_type']>, string> = { REPLACEMENT: 'Replacement requested', NO_REPLACEMENT: 'Closed without replacement', REPLACEMENT_RECEIVED: 'Replacement received and passed QA' };
const badge: Record<CaseStatus, string> = {
  PENDING_REVIEW: 'border-amber-600 bg-amber-600 text-white',
  SENDING: 'border-cyan-600 bg-cyan-600 text-white',
  SENT: 'border-blue-600 bg-blue-600 text-white',
  FAILED: 'border-red-600 bg-red-600 text-white',
  REPLACEMENT_PENDING: 'border-violet-600 bg-violet-600 text-white',
  RESOLVED: 'border-emerald-600 bg-emerald-600 text-white',
};
const dateTime = (value: string | null) => value ? new Intl.DateTimeFormat(undefined, { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(value)) : '—';

function StatusBadge({ status }: { status: CaseStatus }) {
  return <span className={`inline-flex whitespace-nowrap rounded-full border px-2 py-0.5 text-[10px] font-semibold sm:px-2.5 sm:py-1 sm:text-xs ${badge[status]}`}>{labels[status]}</span>;
}

function ResolveCaseModal({ item, disposition, notes, saving, error, onDisposition, onNotes, onCancel, onSubmit }: {
  item: RejectionCase; disposition: Disposition | null; notes: string; saving: boolean; error: string;
  onDisposition: (value: Disposition) => void; onNotes: (value: string) => void; onCancel: () => void; onSubmit: () => void;
}) {
  const notesRequired = disposition === 'NO_REPLACEMENT';
  const notesValid = notesRequired ? notes.trim().length >= 3 : notes.trim().length === 0 || notes.trim().length >= 3;
  const options: { value: Disposition; title: string; body: string; icon: typeof PackageCheck; enabled: boolean }[] = [
    { value: 'REPLACEMENT', title: 'Send to Receiving', body: `Replacement goods are expected from the supplier. A linked replacement receiving for ${item.rejected_quantity} ${item.unit ?? ''} will be created for the original Plant Manager.`, icon: PackageCheck, enabled: item.can_route_to_receiving },
    { value: 'NO_REPLACEMENT', title: 'Close Case', body: 'No replacement delivery is expected. Close the rejection case while retaining its complete history.', icon: Archive, enabled: item.can_close },
  ];
  return <div role="dialog" aria-modal="true" aria-labelledby="resolve-title" aria-describedby="resolve-description" className="fixed inset-0 z-[60] flex items-center justify-center bg-slate-950/80 p-3 sm:p-4"><section className="max-h-[calc(100dvh-1.5rem)] w-full max-w-lg overflow-y-auto rounded-2xl bg-white p-4 shadow-2xl dark:bg-[#111827] sm:max-h-[calc(100dvh-2rem)] sm:p-5">
    <h2 id="resolve-title" className="text-base font-bold sm:text-lg">Resolve rejected item</h2>
    <p id="resolve-description" className="mt-1 text-xs text-slate-600 dark:text-slate-400 sm:text-sm">Choose how this rejected item will be handled. <span className="break-words font-medium text-slate-800 dark:text-slate-200">{item.reference} · {item.product}</span></p>
    <fieldset className="mt-4 space-y-2.5"><legend className="sr-only">Resolution</legend>{options.map(({ value, title, body, icon: Icon, enabled }) => {
      const active = disposition === value;
      return <label key={value} className={`flex min-h-11 gap-3 rounded-xl border p-3 transition-colors ${!enabled ? 'cursor-not-allowed border-slate-200 opacity-50 dark:border-slate-700' : active ? 'cursor-pointer border-cyan-500 bg-cyan-500/10' : 'cursor-pointer border-slate-300 hover:border-cyan-400 dark:border-slate-700'} has-[:focus-visible]:outline-2 has-[:focus-visible]:outline-cyan-500`}>
        <input type="radio" name="disposition" value={value} checked={active} disabled={!enabled || saving} onChange={() => onDisposition(value)} className="sr-only" />
        <Icon className={`mt-0.5 h-4 w-4 shrink-0 sm:h-5 sm:w-5 ${active ? 'text-cyan-600 dark:text-cyan-300' : 'text-slate-500'}`} aria-hidden="true" />
        <span className="min-w-0"><span className="block text-xs font-semibold sm:text-sm">{title}</span><span className="mt-0.5 block text-[11px] leading-snug text-slate-600 dark:text-slate-400 sm:text-xs">{body}</span></span>
      </label>;
    })}</fieldset>
    <label className="mt-4 block text-xs font-medium sm:text-sm">Resolution notes <span className="font-normal text-slate-500">{notesRequired ? '(required)' : '(optional)'}</span><textarea value={notes} onChange={(event) => onNotes(event.target.value)} rows={3} maxLength={2000} required={notesRequired} placeholder={notesRequired ? 'e.g. Supplier issued credit, replacement no longer required' : 'Optional note for the replacement request'} className="mt-1.5 w-full rounded-xl border border-slate-300 bg-transparent p-2.5 text-xs placeholder:text-slate-400 focus:border-cyan-500 focus:outline-none dark:border-slate-700 sm:p-3 sm:text-sm" /></label>
    {error && <p role="alert" className="mt-3 flex items-start gap-2 rounded-lg bg-amber-500/10 p-2.5 text-xs text-amber-800 dark:text-amber-200 sm:text-sm"><AlertTriangle className="mt-0.5 h-4 w-4 shrink-0" />{error}</p>}
    <div className="mt-5 flex flex-col-reverse gap-2 sm:flex-row sm:gap-3"><button type="button" disabled={saving} onClick={onCancel} className="min-h-11 rounded-xl border border-slate-300 px-4 text-xs font-semibold focus-visible:outline-2 focus-visible:outline-cyan-500 dark:border-slate-700 sm:flex-1 sm:text-sm">Cancel</button><button type="button" disabled={saving || !disposition || !notesValid} onClick={onSubmit} className="inline-flex min-h-11 items-center justify-center gap-2 rounded-xl bg-cyan-600 px-4 text-xs font-semibold text-white hover:bg-cyan-700 focus-visible:outline-2 focus-visible:outline-cyan-500 disabled:cursor-not-allowed disabled:opacity-50 sm:flex-1 sm:text-sm">{saving && <Loader2 className="h-4 w-4 animate-spin" />}{disposition === 'NO_REPLACEMENT' ? 'Close Case' : 'Send to Receiving'}</button></div>
  </section></div>;
}

export default function AdminRejectedItems() {
  const [cases, setCases] = useState<RejectionCase[]>([]);
  const [search, setSearch] = useState('');
  const [status, setStatus] = useState<'ALL' | CaseStatus>('ALL');
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');
  const [selected, setSelected] = useState<RejectionCase | null>(null);
  const [confirm, setConfirm] = useState<'send' | 'resolve' | null>(null);
  const [notes, setNotes] = useState('');
  const [disposition, setDisposition] = useState<Disposition | null>(null);
  const [saving, setSaving] = useState(false);
  const [notice, setNotice] = useState('');
  const [viewMode, setViewMode] = useState<'table' | 'grid'>(() => window.matchMedia('(max-width: 767px)').matches ? 'grid' : 'table');

  const load = useCallback(async () => {
    setLoading(true);
    try {
      const response = await apiClient.get('/admin/rejected-items');
      setCases(response.data?.data ?? []); setError('');
    } catch (requestError: any) {
      setError(requestError?.response?.data?.message || 'Unable to load rejected item cases.');
    } finally { setLoading(false); }
  }, []);
  useEffect(() => { void load(); }, [load]);

  const filtered = useMemo(() => cases.filter((item) => {
    const needle = search.trim().toLowerCase();
    const matches = !needle || [item.reference, item.product, item.receiving.number, item.purchase_order?.number, item.registered_supplier?.name, item.original_supplier_name].some((value) => value?.toLowerCase().includes(needle));
    return matches && (status === 'ALL' || item.status === status);
  }), [cases, search, status]);
  const totals = useMemo(() => ({ pending: cases.filter((item) => item.status === 'PENDING_REVIEW').length, failed: cases.filter((item) => item.status === 'FAILED').length, sent: cases.filter((item) => item.status === 'SENT').length, resolved: cases.filter((item) => item.status === 'RESOLVED').length }), [cases]);

  const updateCase = (updated: RejectionCase) => { setCases((current) => current.map((item) => item.id === updated.id ? updated : item)); setSelected(updated); };
  const submit = async () => {
    if (!selected || !confirm) return;
    setSaving(true); setNotice('');
    try {
      const response = confirm === 'send'
        ? await apiClient.post(`/admin/rejected-items/${selected.id}/send`)
        : await apiClient.post(`/admin/rejected-items/${selected.id}/resolve`, { resolution_type: disposition, resolution_notes: notes.trim() || null });
      updateCase(response.data.data); setNotice(response.data.message); setConfirm(null); setNotes(''); setDisposition(null);
    } catch (requestError: any) {
      setNotice(requestError?.response?.data?.message || 'The action could not be completed.');
      if (confirm === 'send' || requestError?.response?.status === 422) await load();
    } finally { setSaving(false); }
  };

  return <main className="min-h-full overflow-y-auto bg-slate-50 px-4 pb-10 pt-4 text-slate-900 dark:bg-[#090d16] dark:text-slate-100 sm:px-6 sm:pt-6 xl:px-8 xl:pt-8">
    <div className="mx-auto max-w-7xl space-y-6">
      <header className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><h1 className="text-2xl font-bold sm:text-3xl">Rejected Items</h1><p className="mt-2 max-w-2xl text-sm text-slate-600 dark:text-slate-400">Review QA rejections, notify the original supplier, and record the final resolution.</p></div><button type="button" onClick={() => void load()} disabled={loading} className="inline-flex min-h-10 items-center justify-center gap-2 self-start rounded-xl border border-slate-300 px-4 text-sm font-semibold hover:bg-white focus-visible:outline-2 focus-visible:outline-cyan-500 disabled:opacity-50 dark:border-slate-700 dark:hover:bg-slate-800 sm:min-h-11 sm:self-auto"><RefreshCw className={`h-4 w-4 ${loading ? 'animate-spin' : ''}`} />Refresh</button></header>
      <section aria-label="Case totals" className="grid grid-cols-2 gap-3 lg:grid-cols-4">{[['Pending review', totals.pending, 'text-amber-600'], ['Delivery failed', totals.failed, 'text-red-600'], ['Sent', totals.sent, 'text-blue-600'], ['Resolved', totals.resolved, 'text-emerald-600']].map(([label, value, color]) => <article key={String(label)} className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm dark:border-slate-800 dark:bg-[#0d1322]"><p className="text-xs font-semibold uppercase tracking-wide text-slate-500">{label}</p><p className={`mt-2 text-2xl font-bold ${color}`}>{value}</p></article>)}</section>
      <section className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm dark:border-slate-800 dark:bg-[#0d1322]">
        <div className="space-y-2.5 md:grid md:grid-cols-[1fr_auto] md:items-center md:gap-3 md:space-y-0"><label className="relative block w-full"><span className="sr-only">Search rejected items</span><Search className="pointer-events-none absolute left-3 top-1/2 h-3.5 w-3.5 -translate-y-1/2 text-slate-400 sm:h-4 sm:w-4" /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search case, PO, receiving, supplier, product..." className="h-10 w-full rounded-xl border border-slate-300 bg-transparent pl-9 pr-3 text-xs placeholder:text-xs focus:border-cyan-500 focus:outline-none dark:border-slate-700 sm:h-11 sm:pl-10 sm:text-sm sm:placeholder:text-sm" /></label><div className="flex min-w-0 items-center gap-2"><label className="min-w-0 flex-1 md:w-48 md:flex-none"><span className="sr-only">Filter by status</span><select value={status} onChange={(event) => setStatus(event.target.value as typeof status)} className="h-10 w-full rounded-xl border border-slate-300 bg-white px-3 text-xs dark:border-slate-700 dark:bg-[#0d1322] sm:h-11 sm:text-sm"><option value="ALL">Status</option>{(['PENDING_REVIEW', 'SENT', 'FAILED', 'REPLACEMENT_PENDING', 'RESOLVED'] as CaseStatus[]).map((value) => <option key={value} value={value}>{labels[value]}</option>)}</select></label><div className="admin-rejected-view-toggle flex shrink-0 rounded-lg border border-slate-300 bg-slate-50 p-0.5 dark:border-slate-700 dark:bg-slate-900" role="group" aria-label="Choose rejected items view"><button type="button" onClick={() => setViewMode('table')} aria-label="Table view" aria-pressed={viewMode === 'table'} title="Table view" className={`admin-rejected-view-button flex h-[34px] w-[34px] items-center justify-center rounded-lg transition-colors focus-visible:outline-2 focus-visible:outline-cyan-500 ${viewMode === 'table' ? 'bg-white text-cyan-700 shadow-sm dark:bg-slate-700 dark:text-cyan-300' : 'text-slate-500 hover:text-slate-900 dark:hover:text-white'}`}><LayoutList className="h-3.5 w-3.5" /></button><button type="button" onClick={() => setViewMode('grid')} aria-label="Grid view" aria-pressed={viewMode === 'grid'} title="Grid view" className={`admin-rejected-view-button flex h-[34px] w-[34px] items-center justify-center rounded-lg transition-colors focus-visible:outline-2 focus-visible:outline-cyan-500 ${viewMode === 'grid' ? 'bg-white text-cyan-700 shadow-sm dark:bg-slate-700 dark:text-cyan-300' : 'text-slate-500 hover:text-slate-900 dark:hover:text-white'}`}><LayoutGrid className="h-3.5 w-3.5" /></button></div></div></div>
        {error && <p role="alert" className="mt-4 rounded-xl bg-red-500/10 p-3 text-sm text-red-700 dark:text-red-300">{error}</p>}
        {loading ? <div className="flex min-h-52 items-center justify-center"><Loader2 className="h-7 w-7 animate-spin text-cyan-500" /><span className="sr-only">Loading cases</span></div> : filtered.length === 0 ? <div className="py-16 text-center"><CheckCircle2 className="mx-auto h-10 w-10 text-emerald-500" /><p className="mt-3 font-semibold">No matching rejected item cases</p><p className="mt-1 text-sm text-slate-500">New completed QA rejections will appear here automatically.</p></div> : <>
          {viewMode === 'grid' && <div className="mt-4 grid gap-2.5 md:grid-cols-2 xl:grid-cols-3">{filtered.map((item) => <article key={item.id} className="rounded-xl border border-slate-200 p-3 dark:border-slate-700 sm:p-4"><div className="flex items-start justify-between gap-2"><div className="min-w-0"><p className="line-clamp-2 text-xs font-semibold sm:text-sm" title={item.product}>{item.product}</p><p className="mt-0.5 text-[10px] text-slate-500 sm:text-xs">{item.receiving.number} · {item.purchase_order?.number ?? 'PO unavailable'}</p></div><StatusBadge status={item.status} /></div><p className="mt-2 line-clamp-2 text-xs text-slate-600 dark:text-slate-300 sm:text-sm" title={item.supplier.name}>{item.supplier.name}</p><dl className="mt-2.5 grid grid-cols-2 gap-2 text-xs sm:text-sm"><div><dt className="text-[10px] uppercase tracking-wide text-slate-500 sm:text-xs">Rejected</dt><dd className="font-semibold text-red-600">{item.rejected_quantity} / {item.delivered_quantity} {item.unit}</dd></div><div><dt className="text-[10px] uppercase tracking-wide text-slate-500 sm:text-xs">Evidence</dt><dd className="flex items-center gap-1"><Eye className="h-3.5 w-3.5" aria-hidden="true" />{item.attachments.length} files</dd></div></dl><div className="mt-3 grid grid-cols-2 gap-2"><button type="button" onClick={() => { setSelected(item); setNotice(''); }} className="inline-flex min-h-9 items-center justify-center gap-1.5 rounded-lg border border-slate-300 px-2.5 text-[11px] font-semibold focus-visible:outline-2 focus-visible:outline-cyan-500 dark:border-slate-700 sm:min-h-10 sm:text-xs"><Eye className="h-3.5 w-3.5" />Review</button>{item.status !== 'RESOLVED' && <button type="button" disabled={!item.can_send} title={item.send_block_reason ?? undefined} onClick={() => { setSelected(item); setConfirm('send'); setNotice(''); }} className="inline-flex min-h-9 items-center justify-center gap-1.5 rounded-lg bg-cyan-600 px-2.5 text-[11px] font-semibold text-white disabled:cursor-not-allowed disabled:opacity-50 sm:min-h-10 sm:text-xs"><Send className="h-3.5 w-3.5" />{item.sent_at ? 'Resend' : 'Send'}</button>}</div></article>)}</div>}
          {viewMode === 'table' && <div className="mt-4 max-w-full overflow-x-auto rounded-xl border border-slate-200 dark:border-slate-700"><table className="w-full min-w-[900px] table-fixed text-left text-xs sm:text-sm"><thead className="border-b border-slate-200 bg-slate-100 text-[10px] uppercase tracking-wide text-slate-500 dark:border-slate-700 dark:bg-slate-900 sm:text-[11px]"><tr><th className="sticky left-0 z-20 w-[120px] bg-slate-100 px-2 py-2.5 dark:bg-slate-900 sm:px-3 sm:py-3">Receiving / PO</th><th className="w-36 px-2 py-2.5 sm:px-3 sm:py-3">Inspection</th><th className="w-40 px-2 py-2.5 sm:px-3 sm:py-3">Supplier</th><th className="w-44 px-2 py-2.5 sm:px-3 sm:py-3">Product</th><th className="w-40 px-2 py-2.5 sm:px-3 sm:py-3">Delivered / Rejected</th><th className="w-24 px-2 py-2.5 sm:px-3 sm:py-3">Evidence</th><th className="w-28 px-2 py-2.5 sm:px-3 sm:py-3">Status</th><th className="w-24 px-2 py-2.5 text-right sm:px-3 sm:py-3">Action</th></tr></thead><tbody>{filtered.map((item) => <tr key={item.id} className="border-b border-slate-100 bg-white dark:border-slate-800 dark:bg-[#0d1322]"><td className="sticky left-0 z-10 w-[120px] bg-white px-2 py-2.5 shadow-[1px_0_0_0_rgb(226_232_240)] dark:bg-[#0d1322] dark:shadow-[1px_0_0_0_rgb(51_65_85)] sm:px-3 sm:py-3"><p className="truncate font-semibold" title={item.receiving.number}>{item.receiving.number}</p><p className="truncate text-[10px] text-slate-500 sm:text-[11px]" title={item.purchase_order?.number ?? 'PO unavailable'}>{item.purchase_order?.number ?? 'PO unavailable'}</p></td><td className="whitespace-nowrap px-2 py-2.5 sm:px-3 sm:py-3">{dateTime(item.inspection_date)}</td><td className="truncate px-2 py-2.5 sm:px-3 sm:py-3" title={item.supplier.name}>{item.supplier.name}</td><td className="truncate px-2 py-2.5 sm:px-3 sm:py-3" title={item.product}>{item.product}</td><td className="whitespace-nowrap px-2 py-2.5 sm:px-3 sm:py-3"><span>{item.delivered_quantity}</span> / <span className="font-semibold text-red-600">{item.rejected_quantity} {item.unit}</span></td><td className="px-2 py-2.5 sm:px-3 sm:py-3"><span className="inline-flex items-center gap-1 whitespace-nowrap"><Eye className="h-3.5 w-3.5 sm:h-4 sm:w-4" aria-hidden="true" />{item.attachments.length} files</span></td><td className="px-2 py-2.5 sm:px-3 sm:py-3"><StatusBadge status={item.status} /></td><td className="px-2 py-2.5 text-right sm:px-3 sm:py-3"><button type="button" onClick={() => { setSelected(item); setNotice(''); }} className="min-h-9 rounded-lg px-2.5 text-[11px] font-semibold text-cyan-700 hover:bg-cyan-500/10 focus-visible:outline-2 focus-visible:outline-cyan-500 dark:text-cyan-300 sm:min-h-10 sm:px-3 sm:text-xs">Review</button></td></tr>)}</tbody></table></div>}
        </>}
      </section>
    </div>
    {selected && <div role="dialog" aria-modal="true" aria-labelledby="case-title" onClick={() => setSelected(null)} className="fixed inset-0 z-50 flex justify-end bg-slate-950/70"><section onClick={(event) => event.stopPropagation()} className="flex h-dvh w-full flex-col overflow-hidden bg-white shadow-2xl dark:bg-[#0d1322] sm:max-w-2xl"><div className="flex shrink-0 items-start justify-between gap-3 border-b border-slate-200 px-4 py-3 dark:border-slate-700 sm:px-6 sm:py-4"><div className="min-w-0"><p className="text-xs text-slate-500 sm:text-sm">{selected.reference}</p><h2 id="case-title" className="truncate text-lg font-bold sm:text-xl" title={selected.product}>{selected.product}</h2><div className="mt-1.5 flex flex-wrap items-center gap-1.5"><StatusBadge status={selected.status} />{selected.receiving.replacement_for_reference && <span className="inline-flex whitespace-nowrap rounded-full border border-violet-500/30 bg-violet-500/10 px-2 py-0.5 text-[10px] font-semibold text-violet-700 dark:text-violet-300 sm:px-2.5 sm:py-1 sm:text-xs">Replacement for {selected.receiving.replacement_for_reference}</span>}</div></div><button type="button" onClick={() => setSelected(null)} aria-label="Close case details" className="flex h-10 w-10 shrink-0 items-center justify-center rounded-lg hover:bg-slate-100 focus-visible:outline-2 focus-visible:outline-cyan-500 dark:hover:bg-slate-800"><X className="h-5 w-5" /></button></div><div className="min-h-0 flex-1 overflow-y-auto px-4 pb-8 sm:px-6">
      {selected.supplier_error && <div className="mt-5 rounded-xl border border-amber-500/30 bg-amber-500/10 p-4 text-sm text-amber-800 dark:text-amber-200"><div className="flex gap-3"><AlertTriangle className="h-5 w-5 shrink-0" /><p>{selected.supplier_error}</p></div></div>}
      <dl className="mt-6 grid gap-4 rounded-xl bg-slate-50 p-4 text-sm dark:bg-slate-900/60 sm:grid-cols-2">{[['Original supplier', selected.original_supplier_name], ['Registered supplier', selected.registered_supplier?.name ?? 'Unavailable'], ['Supplier code', selected.registered_supplier?.code ?? 'Unavailable'], ['Supplier email', selected.registered_supplier?.email ?? 'Unavailable'], ['Purchase order', selected.purchase_order?.number ?? 'Unavailable'], ['Receiving', selected.receiving.number], ['Delivery / reference', `${selected.receiving.delivery_date ?? 'Unavailable'} · ${selected.receiving.reference_number ?? 'No reference'}`], ['Delivered quantity', `${selected.delivered_quantity} ${selected.unit ?? ''}`], ['Accepted quantity', `${selected.accepted_quantity} ${selected.unit ?? ''}`], ['Rejected quantity', `${selected.rejected_quantity} ${selected.unit ?? ''}`], ['Inspection', dateTime(selected.inspection_date)], ['Inspected by', selected.inspected_by ?? 'Unavailable'], ['QA result', selected.inspection_result], ['Send attempts', String(selected.send_attempts)]].map(([term, value]) => <div key={term}><dt className="text-xs uppercase tracking-wide text-slate-500">{term}</dt><dd className="mt-1 break-words font-medium">{value}</dd></div>)}</dl>
      <section className="mt-6"><h3 className="font-semibold">QA findings</h3><p className="mt-2 whitespace-pre-wrap rounded-xl border border-slate-200 p-4 text-sm dark:border-slate-700">{selected.reason || 'No additional remarks were recorded.'}</p></section><section className="mt-6"><EvidenceGallery attachments={selected.attachments} receivingId={selected.receiving.id} /></section>
      {(selected.sent_at || selected.resolved_at || selected.last_error || selected.replacement_receiving) && <section className="mt-6 space-y-2 rounded-xl border border-slate-200 p-4 text-sm dark:border-slate-700"><h3 className="font-semibold">Case activity</h3>{selected.sent_at && <p>Sent {dateTime(selected.sent_at)} by {selected.sent_by ?? 'Admin'}.</p>}{selected.last_error && <p className="text-red-700 dark:text-red-300">Last attempt failed {dateTime(selected.last_error_at)}. {selected.last_error}</p>}{selected.replacement_receiving && <p>Routed to Receiving {dateTime(selected.routed_to_receiving_at)} by {selected.routed_by ?? 'Admin'} as <span className="font-semibold">{selected.replacement_receiving.number}</span> ({selected.replacement_receiving.expected_quantity} {selected.unit ?? ''} expected · {selected.replacement_receiving.status}).</p>}{selected.resolved_at && <p>Resolved {dateTime(selected.resolved_at)} by {selected.resolved_by ?? 'System'}{selected.resolution_type ? ` · ${resolutionLabels[selected.resolution_type]}` : ''}.</p>}{selected.resolution_notes && <p className="whitespace-pre-wrap text-slate-600 dark:text-slate-300">Notes: {selected.resolution_notes}</p>}</section>}
      </div>{(notice || selected.status !== 'RESOLVED') && <footer className="relative z-10 shrink-0 border-t border-slate-200 bg-white px-4 py-3 shadow-[0_-8px_20px_rgba(15,23,42,0.08)] dark:border-slate-700 dark:bg-[#0d1322] sm:px-6 sm:py-4">{(notice || (selected.send_block_reason && selected.send_block_reason !== selected.supplier_error)) && <p role="status" className={`mb-3 flex items-start gap-2 rounded-lg p-2.5 text-xs sm:text-sm ${notice && !notice.toLowerCase().includes('could not') && !notice.toLowerCase().includes('unavailable') ? 'bg-emerald-500/10 text-emerald-700 dark:text-emerald-300' : 'bg-amber-500/10 text-amber-800 dark:text-amber-200'}`}><AlertTriangle className="mt-0.5 h-4 w-4 shrink-0" />{notice || selected.send_block_reason}</p>}{selected.status !== 'RESOLVED' && <div className="grid grid-cols-2 gap-2 sm:gap-3"><button type="button" disabled={!selected.can_send || saving} onClick={() => setConfirm('send')} className="inline-flex min-h-10 items-center justify-center gap-1.5 rounded-xl bg-cyan-600 px-2 text-xs font-semibold text-white hover:bg-cyan-700 disabled:cursor-not-allowed disabled:opacity-50 sm:min-h-11 sm:px-4 sm:text-sm"><Send className="h-3.5 w-3.5 sm:h-4 sm:w-4" />{selected.sent_at ? 'Resend report' : 'Send to supplier'}</button><button type="button" disabled={saving || !selected.can_resolve} aria-describedby={!selected.can_resolve && selected.resolve_block_reason ? 'resolve-hint' : undefined} title={!selected.can_resolve ? selected.resolve_block_reason ?? undefined : undefined} onClick={() => { setDisposition(selected.can_route_to_receiving ? null : 'NO_REPLACEMENT'); setNotes(''); setNotice(''); setConfirm('resolve'); }} className="inline-flex min-h-10 items-center justify-center gap-1.5 rounded-xl border border-emerald-600 px-2 text-xs font-semibold text-emerald-700 hover:bg-emerald-500/10 disabled:cursor-not-allowed disabled:border-slate-300 disabled:text-slate-400 disabled:hover:bg-transparent dark:text-emerald-300 dark:disabled:border-slate-700 dark:disabled:text-slate-500 sm:min-h-11 sm:px-4 sm:text-sm"><CheckCircle2 className="h-3.5 w-3.5 sm:h-4 sm:w-4" />Resolve Case</button></div>}{selected.status !== 'RESOLVED' && !selected.can_resolve && selected.resolve_block_reason && <p id="resolve-hint" className="mt-2 text-[11px] leading-snug text-slate-500 dark:text-slate-400 sm:text-xs">{selected.resolve_block_reason}</p>}</footer>}</section></div>}
    {confirm === 'send' && selected && <div role="dialog" aria-modal="true" aria-labelledby="confirm-title" className="fixed inset-0 z-[60] flex items-center justify-center bg-slate-950/80 p-4"><section className="max-h-[calc(100dvh-2rem)] w-full max-w-md overflow-y-auto rounded-2xl bg-white p-5 shadow-2xl dark:bg-[#111827]"><h2 id="confirm-title" className="text-lg font-bold">{selected.sent_at ? 'Resend Rejection Report?' : 'Send Rejection Report?'}</h2><dl className="mt-4 grid grid-cols-[auto_1fr] gap-x-3 gap-y-2 text-sm"><dt className="text-slate-500">Supplier</dt><dd className="break-words font-medium">{selected.registered_supplier?.name}</dd><dt className="text-slate-500">Email</dt><dd className="break-all font-medium">{selected.registered_supplier?.email}</dd><dt className="text-slate-500">Purchase Order</dt><dd>{selected.purchase_order?.number}</dd><dt className="text-slate-500">Receiving</dt><dd>{selected.receiving.number}</dd><dt className="text-slate-500">Product</dt><dd className="break-words">{selected.product}</dd><dt className="text-slate-500">Rejected</dt><dd>{selected.rejected_quantity} / {selected.delivered_quantity} {selected.unit}</dd></dl><div className="mt-5 flex gap-3"><button type="button" disabled={saving} onClick={() => setConfirm(null)} className="min-h-10 flex-1 rounded-xl border border-slate-300 text-xs font-semibold dark:border-slate-700 sm:min-h-11 sm:text-sm">Cancel</button><button type="button" disabled={saving} onClick={() => void submit()} className="inline-flex min-h-10 flex-1 items-center justify-center gap-2 rounded-xl bg-cyan-600 text-xs font-semibold text-white disabled:opacity-50 sm:min-h-11 sm:text-sm">{saving && <Loader2 className="h-4 w-4 animate-spin" />}Send Report</button></div></section></div>}
    {confirm === 'resolve' && selected && <ResolveCaseModal item={selected} disposition={disposition} notes={notes} saving={saving} error={notice} onDisposition={setDisposition} onNotes={setNotes} onCancel={() => { setConfirm(null); setDisposition(null); setNotes(''); }} onSubmit={() => void submit()} />}
  </main>;
}
