import { useCallback, useEffect, useState } from 'react';
import { CalendarPlus, Check, Download, Eye, FileText, Image as ImageIcon, Plus, RefreshCw, Search, X } from 'lucide-react';
import { useSearchParams } from 'react-router-dom';
import { apiClient } from '../../lib/api';

type Status = 'PENDING' | 'UNDER_REVIEW' | 'NEEDS_REVISION' | 'QUALIFIED_FOR_MEETING' | 'MEETING_SCHEDULED' | 'MEETING_COMPLETED' | 'APPROVED' | 'REJECTED';
type AttachmentType = 'BUSINESS_CERTIFICATE' | 'BUSINESS_PERMIT' | 'PRODUCT_SERVICE_IMAGE';
type Attachment = { id: number; attachment_type: AttachmentType; original_name: string; mime_type: string; file_size: number; preview_url: string; download_url: string };
type ChecklistKey = 'requirements_discussed' | 'product_capability_verified' | 'delivery_capability_verified' | 'compliance_requirements_discussed';
type Assessment = 'RECOMMEND_APPROVAL' | 'NEEDS_FURTHER_REVIEW' | 'RECOMMEND_REJECTION';
type Evaluation = Record<ChecklistKey, boolean> & { overall_assessment: Assessment };
type Slot = { id: number; scheduled_at: string; starts_at?: string; ends_at?: string; selected_at?: string | null; status: 'AVAILABLE' | 'RESERVED' | 'COMPLETED' | 'CANCELLED'; evaluation_notes?: string | null; evaluation?: Evaluation | null };
type Event = { id: number; title: string; description?: string; occurred_at: string };
type Offering = { id: number; type: 'PRODUCT' | 'SERVICE'; name: string; category: string | null; description: string | null; mapped_product?: { id: number; name: string } | null };
type Application = {
  id: number; application_number: string; company_name: string; owner_name?: string | null; address: string; contact_person: string; email: string; phone: string;
  business_type: string; supply_category: string; products_services: string | null; offerings?: Offering[]; status: Status; submitted_at: string; supplier_message?: string | null;
  decision_reason?: string | null; alternative_schedule_message?: string | null; alternative_schedule_requested_at?: string | null;
  approved_supplier?: { supplier_code: string; name: string }; attachments?: Attachment[]; meeting_slots?: Slot[]; events?: Event[];
};
type Step = 'review' | 'scheduling' | 'meeting' | 'decision';
type Mode = 'revision' | 'reject' | null;
type Draft = { date: string; start_time: string; end_time: string };
type Reason = { code: string; label: string };

const revisionReasons: Reason[] = [
  ['BUSINESS_CERTIFICATE', 'Business Certificate is invalid or requires correction'], ['BUSINESS_PERMIT', 'Business Permit is invalid, expired, or requires correction'],
  ['PRODUCT_SERVICE_IMAGE', 'Product / Service image is unclear or incorrect'], ['UNREADABLE_DOCUMENT', 'Submitted document is unreadable'],
  ['INFORMATION_MISMATCH', 'Submitted information does not match the document'], ['INCOMPLETE_INFORMATION', 'Required information is incomplete'], ['OTHER', 'Other'],
].map(([code, label]) => ({ code, label }));
const initialRejectReasons: Reason[] = [
  ['INELIGIBLE', 'Does not meet supplier eligibility requirements'], ['DOCUMENTS_CANNOT_BE_VALIDATED', 'Required business documentation cannot be validated'],
  ['OUTSIDE_CURRENT_REQUIREMENTS', 'Product / service offering is outside current requirements'], ['COMPLIANCE_NOT_SATISFIED', 'Compliance requirements are not satisfied'], ['OTHER', 'Other'],
].map(([code, label]) => ({ code, label }));
const finalRejectReasons: Reason[] = [
  ['SUPPLIER_REQUIREMENTS_NOT_MET', 'Does not meet supplier requirements'], ['CAPABILITY_NOT_MET', 'Product / service capability did not meet requirements'],
  ['DELIVERY_CONCERNS', 'Delivery capability concerns'], ['COMMERCIAL_TERMS_UNACCEPTABLE', 'Business / commercial terms are not acceptable'],
  ['COMPLIANCE_NOT_SATISFIED', 'Compliance requirements are not satisfied'], ['OTHER', 'Other'],
].map(([code, label]) => ({ code, label }));
const statuses: Status[] = ['PENDING', 'UNDER_REVIEW', 'NEEDS_REVISION', 'QUALIFIED_FOR_MEETING', 'MEETING_SCHEDULED', 'MEETING_COMPLETED', 'APPROVED', 'REJECTED'];
const statusStyle: Record<Status, string> = {
  PENDING: 'border-amber-500/30 text-amber-700 dark:text-amber-300', UNDER_REVIEW: 'border-sky-500/30 text-sky-700 dark:text-sky-300',
  NEEDS_REVISION: 'border-orange-500/30 text-orange-700 dark:text-orange-300', QUALIFIED_FOR_MEETING: 'border-cyan-500/30 text-cyan-700 dark:text-cyan-300',
  MEETING_SCHEDULED: 'border-violet-500/30 text-violet-700 dark:text-violet-300', MEETING_COMPLETED: 'border-indigo-500/30 text-indigo-700 dark:text-indigo-300',
  APPROVED: 'border-emerald-500/30 text-emerald-700 dark:text-emerald-300', REJECTED: 'border-rose-500/30 text-rose-700 dark:text-rose-300',
};
const emptyDraft = (): Draft => ({ date: '', start_time: '', end_time: '' });
const checklistItems: [ChecklistKey, string][] = [['requirements_discussed', 'Requirements discussed'], ['product_capability_verified', 'Product capability verified'], ['delivery_capability_verified', 'Delivery capability verified'], ['compliance_requirements_discussed', 'Compliance requirements discussed']];
// An assessment is an internal record only; the final decision stays in Step 4.
const assessmentLabels: Record<Assessment, string> = { RECOMMEND_APPROVAL: 'Recommend for Approval', NEEDS_FURTHER_REVIEW: 'Needs Further Review', RECOMMEND_REJECTION: 'Recommend for Rejection' };
type EvaluationForm = Record<ChecklistKey, boolean> & { overall_assessment: Assessment | ''; notes: string };
const emptyEvaluation = (): EvaluationForm => ({ requirements_discussed: false, product_capability_verified: false, delivery_capability_verified: false, compliance_requirements_discussed: false, overall_assessment: '', notes: '' });
const statusStep = (status: Status): Step => status === 'QUALIFIED_FOR_MEETING' ? 'scheduling' : status === 'MEETING_SCHEDULED' ? 'meeting' : ['MEETING_COMPLETED', 'APPROVED', 'REJECTED'].includes(status) ? 'decision' : 'review';
const labelStatus = (status: string) => status.replaceAll('_', ' ');
const manilaDate = (value: string) => new Intl.DateTimeFormat('en-PH', { timeZone: 'Asia/Manila', dateStyle: 'long' }).format(new Date(value));
const manilaTime = (value: string) => new Intl.DateTimeFormat('en-PH', { timeZone: 'Asia/Manila', timeStyle: 'short' }).format(new Date(value));
const slotStart = (slot: Slot) => slot.starts_at || slot.scheduled_at;
const slotEnd = (slot: Slot) => slot.ends_at || new Date(new Date(slotStart(slot)).getTime() + 3600000).toISOString();
const slotTimes = (slot: Slot) => `${manilaTime(slotStart(slot))} – ${manilaTime(slotEnd(slot))}`;
/** Mirrors backend publish validation; the backend remains authoritative. */
const validateDrafts = (drafts: Draft[]): string => {
  if (drafts.length < 3) return 'Publish at least three meeting options.';
  if (drafts.some((draft) => !draft.date || !draft.start_time || !draft.end_time)) return 'Every meeting option needs a date, start time, and end time.';
  if (drafts.some((draft) => draft.end_time <= draft.start_time)) return 'Every meeting option must end after it starts.';
  if (new Set(drafts.map((draft) => draft.date)).size !== drafts.length) return 'Each meeting option must use a different date.';
  return '';
};
const manila = (value: string, timeOnly = false) => new Intl.DateTimeFormat('en-PH', { timeZone: 'Asia/Manila', ...(timeOnly ? { timeStyle: 'short' as const } : { dateStyle: 'long' as const, timeStyle: 'short' as const }) }).format(new Date(value));
const apiError = (error: any, fallback: string) => error?.response?.data?.errors ? String(Object.values(error.response.data.errors).flat()[0]) : error?.response?.data?.message || fallback;

export default function SupplierApplicationsTab() {
  const [items, setItems] = useState<Application[]>([]); const [selected, setSelected] = useState<Application | null>(null);
  const [search, setSearch] = useState(''); const [status, setStatus] = useState(''); const [pending, setPending] = useState(0);
  const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState('');
  // The active step is derived from backend status; `qualifying` only opens the scheduling draft from review.
  const [qualifying, setQualifying] = useState(false); const [replacing, setReplacing] = useState(false); const [scheduleError, setScheduleError] = useState(''); const [mode, setMode] = useState<Mode>(null); const [codes, setCodes] = useState<string[]>([]);
  const [supplierMessage, setSupplierMessage] = useState(''); const [internalNote, setInternalNote] = useState(''); const [evaluation, setEvaluation] = useState<EvaluationForm>(emptyEvaluation); const [now, setNow] = useState(() => Date.now());
  const [drafts, setDrafts] = useState<Draft[]>([emptyDraft(), emptyDraft(), emptyDraft()]); const [confirmApproval, setConfirmApproval] = useState(false);
  const [preview, setPreview] = useState<{ url: string; name: string; mime: string } | null>(null); const [fileBusy, setFileBusy] = useState<number | null>(null);
  const [thumbnails, setThumbnails] = useState<Record<number, string>>({});

  const load = useCallback(async () => { setLoading(true); try { const result = await apiClient.get('/admin/supplier-applications', { params: { search: search || undefined, status: status || undefined } }); setItems(result.data.data || []); setPending(result.data.meta?.pending_action || 0); setError(''); } catch (e: any) { setError(apiError(e, 'Unable to load applications.')); } finally { setLoading(false); } }, [search, status]);
  useEffect(() => { const timer = window.setTimeout(() => void load(), 250); return () => clearTimeout(timer); }, [load]);
  useEffect(() => { let active = true; const urls: string[] = []; const images = selected?.attachments?.filter((file) => file.attachment_type === 'PRODUCT_SERVICE_IMAGE') || []; setThumbnails({}); void Promise.all(images.map(async (file) => { try { const response = await apiClient.get(file.preview_url, { responseType: 'blob' }); const url = URL.createObjectURL(response.data); urls.push(url); return [file.id, url] as const; } catch { return null; } })).then((entries) => active && setThumbnails(Object.fromEntries(entries.filter((entry): entry is readonly [number, string] => entry !== null)))); return () => { active = false; urls.forEach(URL.revokeObjectURL); }; }, [selected]);
  useEffect(() => { const close = (event: KeyboardEvent) => { if (event.key !== 'Escape') return; if (preview) setPreview(null); else if (confirmApproval) setConfirmApproval(false); else setSelected(null); }; document.addEventListener('keydown', close); return () => document.removeEventListener('keydown', close); }, [preview, confirmApproval]);

  const resetForm = () => { setMode(null); setCodes([]); setSupplierMessage(''); setInternalNote(''); };
  const refreshSelected = useCallback(async (id?: number) => { if (!id) return; const result = await apiClient.get(`/admin/supplier-applications/${id}`); setSelected((current) => { if (current && current.status !== result.data.data.status) { setQualifying(false); setReplacing(false); } return result.data.data; }); }, []);
  const selectedId = selected?.id;
  // Notification deep link: ?application=<number>. Resolved through the Admin-only API, exact match only.
  const [searchParams, setSearchParams] = useSearchParams();
  const linkedReference = searchParams.get('application');
  useEffect(() => {
    if (!linkedReference) return;
    let active = true;
    const clearLink = () => setSearchParams((current) => { const next = new URLSearchParams(current); next.delete('application'); return next; }, { replace: true });
    void (async () => {
      try {
        const result = await apiClient.get('/admin/supplier-applications', { params: { search: linkedReference } });
        const match = (result.data.data as Application[] | undefined)?.find((item) => item.application_number === linkedReference);
        if (!active) return;
        if (match) await open(match);
        else setError(`Application ${linkedReference} is not in the active applications list.`);
      } catch (e: any) {
        if (active) setError(apiError(e, 'Unable to open the linked application.'));
      } finally {
        if (active) clearLink();
      }
    })();
    return () => { active = false; };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [linkedReference]);
  // Supplier actions happen elsewhere (portal); refetch when Admin returns to the tab.
  useEffect(() => { if (!selectedId) return; const refetch = () => { if (document.visibilityState === 'visible') void refreshSelected(selectedId).catch(() => undefined); }; window.addEventListener('focus', refetch); document.addEventListener('visibilitychange', refetch); return () => { window.removeEventListener('focus', refetch); document.removeEventListener('visibilitychange', refetch); }; }, [selectedId, refreshSelected]);
  const open = async (application: Application) => { try { if (application.status === 'PENDING') await apiClient.post(`/admin/supplier-applications/${application.id}/review`); setQualifying(false); setReplacing(false); setScheduleError(''); setEvaluation(emptyEvaluation()); await refreshSelected(application.id); resetForm(); setDrafts([emptyDraft(), emptyDraft(), emptyDraft()]); await load(); } catch (e: any) { setError(apiError(e, 'Unable to open application.')); } };
  const decide = async (action: 'revision' | 'reject') => { if (!selected) return; setSaving(true); try { const result = await apiClient.post(`/admin/supplier-applications/${selected.id}/${action}`, { reason_codes: codes, supplier_message: supplierMessage, internal_note: internalNote || undefined }); setSelected(result.data.data); setQualifying(false); resetForm(); await load(); } catch (e: any) { setError(apiError(e, `Unable to ${action} application.`)); } finally { setSaving(false); } };
  const publish = async () => { if (!selected) return; const problem = validateDrafts(drafts); setScheduleError(problem); if (problem) return; setSaving(true); try { await apiClient.post(`/admin/supplier-applications/${selected.id}/meeting-slots`, { slots: drafts }); setDrafts([emptyDraft(), emptyDraft(), emptyDraft()]); setReplacing(false); setQualifying(false); await refreshSelected(selected.id); await load(); } catch (e: any) { setScheduleError(apiError(e, 'Unable to publish meeting options.')); } finally { setSaving(false); } };
  const complete = async (slot: Slot) => { if (!selected) return; if (!evaluation.overall_assessment) { setError('Select an overall assessment before completing the meeting.'); return; } setSaving(true); try { const { notes, ...structured } = evaluation; await apiClient.post(`/admin/supplier-applications/${selected.id}/meeting-slots/${slot.id}/complete`, { ...structured, evaluation_notes: notes.trim() || undefined }); setEvaluation(emptyEvaluation()); await refreshSelected(selected.id); await load(); } catch (e: any) { setError(apiError(e, 'Unable to complete meeting.')); } finally { setSaving(false); } };
  const approve = async () => { if (!selected) return; setSaving(true); try { const result = await apiClient.post(`/admin/supplier-applications/${selected.id}/approve`); setSelected(result.data.data); setConfirmApproval(false); await load(); } catch (e: any) { setError(apiError(e, 'Unable to approve supplier.')); } finally { setSaving(false); } };
  const fileAction = async (file: Attachment, download = false) => { setFileBusy(file.id); try { const response = await apiClient.get(download ? file.download_url : file.preview_url, { responseType: 'blob' }); const url = URL.createObjectURL(response.data); if (download) { const link = document.createElement('a'); link.href = url; link.download = file.original_name; link.click(); setTimeout(() => URL.revokeObjectURL(url), 1000); } else setPreview({ url, name: file.original_name, mime: file.mime_type }); } catch (e: any) { setError(apiError(e, 'Unable to open attachment.')); } finally { setFileBusy(null); } };
  const toggle = (code: string) => setCodes((current) => current.includes(code) ? current.filter((item) => item !== code) : [...current, code]);
  // Re-derive meeting availability locally every 30s while Step 3 is open; no backend polling.
  const meetingOpen = selected?.status === 'MEETING_SCHEDULED';
  useEffect(() => { if (!meetingOpen) return; setNow(Date.now()); const timer = window.setInterval(() => setNow(Date.now()), 30000); return () => window.clearInterval(timer); }, [meetingOpen]);
  const step: Step = selected ? (qualifying && selected.status === 'UNDER_REVIEW' ? 'scheduling' : statusStep(selected.status)) : 'review';
  const available = (selected?.meeting_slots?.filter((slot) => slot.status === 'AVAILABLE' && new Date(slotEnd(slot)).getTime() > Date.now()) || []).sort((a, b) => slotStart(a).localeCompare(slotStart(b)));
  const confirmed = selected?.meeting_slots?.find((slot) => ['RESERVED', 'COMPLETED'].includes(slot.status));
  // Published options are read-only while they await the supplier; new options need an explicit action.
  const showScheduleForm = selected?.status === 'UNDER_REVIEW' || replacing || (selected?.status === 'QUALIFIED_FOR_MEETING' && available.length === 0);
  // Instants are compared directly (timezone-independent); the same ends_at is shown in Asia/Manila.
  const meetingEnded = confirmed ? now >= new Date(slotEnd(confirmed)).getTime() : false;
  const canComplete = meetingEnded && evaluation.overall_assessment !== '' && !saving;
  const duplicateDates = new Set(drafts.map((draft) => draft.date).filter((date, index, all) => date && all.indexOf(date) !== index));
  const reasons = mode === 'revision' ? revisionReasons : selected?.status === 'MEETING_COMPLETED' ? finalRejectReasons : initialRejectReasons;

  const attachments = (type: AttachmentType, title: string, images = false) => { const files = selected?.attachments?.filter((file) => file.attachment_type === type) || []; return <div><h4 className="mb-2 text-xs font-bold uppercase text-[var(--text-muted)]">{title}</h4>{files.length ? <div className={images ? 'grid gap-3 sm:grid-cols-2' : 'space-y-3'}>{files.map((file, index) => <article key={file.id} className="rounded-xl border border-[var(--border-color)] bg-[var(--bg-input)] p-4">{images && thumbnails[file.id] && <img src={thumbnails[file.id]} alt={`Submitted ${title} ${index + 1}`} className="mb-3 h-28 w-full rounded-lg object-cover" />}<div className="flex gap-3">{images ? <ImageIcon className="h-5 w-5 shrink-0 text-cyan-600" /> : <FileText className="h-5 w-5 shrink-0 text-cyan-600" />}<p className="break-all text-sm text-[var(--text-primary)]">{file.original_name}</p></div><div className="mt-3 flex gap-2"><button type="button" disabled={fileBusy === file.id} onClick={() => void fileAction(file)} className="inline-flex min-h-11 items-center gap-2 rounded-lg border border-cyan-600 px-3 text-sm text-cyan-700 dark:text-cyan-300"><Eye className="h-4 w-4" />Preview</button><button type="button" disabled={fileBusy === file.id} onClick={() => void fileAction(file, true)} className="inline-flex min-h-11 items-center gap-2 rounded-lg border border-[var(--border-color)] px-3 text-sm text-[var(--text-primary)]"><Download className="h-4 w-4" />Download</button></div></article>)}</div> : <p className="rounded-xl border border-dashed border-[var(--border-color)] p-4 text-sm text-[var(--text-muted)]">No attachment submitted.</p>}</div>; };

  return <section className="mx-auto w-full max-w-7xl space-y-5 p-4 sm:p-6">
    <header className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><div className="flex items-center gap-2"><h1 className="text-2xl font-bold text-[var(--text-primary)]">Supplier applications</h1>{pending > 0 && <span className="rounded-full bg-amber-500 px-2 py-0.5 text-xs font-bold text-slate-950">{pending} pending</span>}</div><p className="mt-1 text-sm text-[var(--text-muted)]">Review, schedule, evaluate, and make the final supplier decision.</p></div><button type="button" onClick={() => void load()} className="inline-flex min-h-11 items-center justify-center gap-2 rounded-xl border border-[var(--border-color)] px-4 text-sm text-[var(--text-primary)]"><RefreshCw className={`h-4 w-4 ${loading ? 'animate-spin' : ''}`} />Refresh</button></header>
    {error && <div role="alert" className="rounded-xl border border-rose-500/30 bg-rose-500/10 p-3 text-sm text-rose-700 dark:text-rose-300">{error}</div>}
    <div className="grid gap-3 rounded-2xl border border-[var(--border-color)] bg-[var(--bg-card)] p-4 sm:grid-cols-[1fr_240px]"><label className="relative"><span className="sr-only">Search applications</span><Search className="absolute left-3 top-3.5 h-4 w-4 text-[var(--text-muted)]" /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search applications" className="min-h-11 w-full rounded-xl border border-[var(--border-color)] bg-[var(--bg-input)] pl-10 pr-3 text-[var(--text-primary)]" /></label><label><span className="sr-only">Status</span><select value={status} onChange={(event) => setStatus(event.target.value)} className="min-h-11 w-full rounded-xl border border-[var(--border-color)] bg-[var(--bg-input)] px-3 text-[var(--text-primary)]"><option value="">All statuses</option>{statuses.filter((value) => value !== 'REJECTED').map((value) => <option key={value}>{value}</option>)}</select></label></div>
    <div className="overflow-x-auto rounded-2xl border border-[var(--border-color)] bg-[var(--bg-card)]"><table className="w-full min-w-[760px]"><thead className="bg-[var(--bg-hover)] text-left text-xs uppercase text-[var(--text-muted)]"><tr><th className="p-4">Reference</th><th>Company</th><th>Contact</th><th>Status</th><th className="p-4 text-right">Action</th></tr></thead><tbody>{items.map((item) => <tr key={item.id} className="border-t border-[var(--border-color)] text-sm"><td className="p-4 font-mono text-[var(--text-primary)]">{item.application_number}</td><td className="text-[var(--text-primary)]">{item.company_name}</td><td className="text-[var(--text-secondary)]">{item.email}</td><td><span className={`rounded-full border px-2 py-1 text-xs ${statusStyle[item.status]}`}>{labelStatus(item.status)}</span></td><td className="p-4 text-right"><button type="button" onClick={() => void open(item)} className="min-h-11 rounded-lg px-3 font-semibold text-cyan-700 hover:bg-cyan-500/10 dark:text-cyan-300">Review</button></td></tr>)}</tbody></table></div>
    {selected && <div className="fixed inset-0 z-50 flex items-end justify-center bg-slate-950/75 sm:items-center sm:p-6" role="dialog" aria-modal="true" aria-labelledby="application-title"><div className="max-h-[96vh] w-full max-w-4xl overflow-y-auto rounded-t-3xl border border-[var(--border-color)] bg-[var(--bg-card)] p-5 sm:rounded-3xl sm:p-7">
      <header className="sticky -top-5 z-10 bg-[var(--bg-card)] pb-4"><div className="flex justify-between gap-4"><div><p className="font-mono text-xs text-cyan-700 dark:text-cyan-300">{selected.application_number}</p><h2 id="application-title" className="text-2xl font-bold text-[var(--text-primary)]">{selected.company_name}</h2></div><div className="flex gap-1"><button type="button" onClick={() => void refreshSelected(selected.id).catch((e) => setError(apiError(e, 'Unable to refresh application.')))} aria-label="Refresh application" title="Refresh" className="h-11 w-11 rounded-xl hover:bg-[var(--bg-hover)]"><RefreshCw className="mx-auto h-4 w-4" /></button><button type="button" onClick={() => setSelected(null)} aria-label="Close review" className="h-11 w-11 rounded-xl hover:bg-[var(--bg-hover)]"><X className="mx-auto h-5 w-5" /></button></div></div><ol className="mt-4 grid grid-cols-2 gap-2 sm:grid-cols-4" aria-label="Review progress">{(['review', 'scheduling', 'meeting', 'decision'] as Step[]).map((value, index) => <li key={value} aria-current={step === value ? 'step' : undefined} className={`rounded-xl border p-2 text-xs font-semibold ${step === value ? 'border-cyan-500 bg-cyan-500/10 text-cyan-700 dark:text-cyan-300' : 'border-[var(--border-color)] text-[var(--text-muted)]'}`}>{index + 1}. {value === 'decision' ? 'Final Decision' : value[0].toUpperCase() + value.slice(1)}</li>)}</ol></header>
      {step === 'review' && <><div className="grid gap-4 sm:grid-cols-2">{[['Owner', selected.owner_name || 'Not provided'], ['Status', labelStatus(selected.status)], ['Business type', selected.business_type], ['Supply category', selected.supply_category], ['Contact', selected.contact_person], ['Email', selected.email], ['Phone', selected.phone], ['Address', selected.address]].map(([name, value]) => <div key={name}><p className="text-xs font-bold uppercase text-[var(--text-muted)]">{name}</p><p className="mt-1 whitespace-pre-wrap text-sm text-[var(--text-primary)]">{value}</p></div>)}</div><div className="mt-6 grid gap-4 sm:grid-cols-2">{attachments('BUSINESS_CERTIFICATE', 'Business Certificate')}{attachments('BUSINESS_PERMIT', 'Business Permit')}</div><div className="mt-5"><OfferingList offerings={selected.offerings ?? []} approved={selected.status === 'APPROVED'} />{selected.products_services && <><p className="mb-1 mt-4 text-xs font-bold uppercase text-[var(--text-muted)]">{(selected.offerings ?? []).length ? 'Additional capabilities' : 'Products / services (legacy description)'}</p><p className="mb-3 whitespace-pre-wrap text-sm text-[var(--text-primary)]">{selected.products_services}</p></>}{attachments('PRODUCT_SERVICE_IMAGE', 'Product / Service Images', true)}</div>{selected.status === 'NEEDS_REVISION' && <div className="mt-5 rounded-xl border border-orange-500/30 bg-orange-500/10 p-4"><p className="font-semibold text-orange-700 dark:text-orange-300">Waiting for corrections</p><p className="mt-1 text-sm text-[var(--text-primary)]">{selected.supplier_message}</p></div>}{selected.status === 'UNDER_REVIEW' && <div className="mt-6 flex flex-col gap-3 border-t border-[var(--border-color)] pt-5 sm:flex-row sm:justify-end"><button type="button" onClick={() => { setMode('revision'); setCodes([]); }} className="min-h-11 rounded-xl border border-amber-500 px-4 font-semibold text-amber-700 dark:text-amber-300">Return for Revision</button><button type="button" onClick={() => { setMode('reject'); setCodes([]); }} className="min-h-11 rounded-xl border border-rose-500 px-4 font-semibold text-rose-700 dark:text-rose-300">Reject Application</button><button type="button" onClick={() => { resetForm(); setScheduleError(''); setQualifying(true); }} className="min-h-11 rounded-xl bg-cyan-700 px-4 font-semibold text-white">Qualify for Meeting</button></div>}{mode && <ReasonForm title={mode === 'revision' ? 'Return for Revision' : 'Reject Application'} reasons={reasons} codes={codes} toggle={toggle} supplierMessage={supplierMessage} setSupplierMessage={setSupplierMessage} internalNote={internalNote} setInternalNote={setInternalNote} cancel={resetForm} submit={() => void decide(mode)} saving={saving} destructive={mode === 'reject'} />}</>}
      {step === 'scheduling' && <><h3 className="text-xl font-bold text-[var(--text-primary)]">Meeting Scheduling</h3><p className="mt-1 text-sm text-[var(--text-muted)]">All times use Asia/Manila.</p>
        {selected.alternative_schedule_requested_at && <div className="mt-4 rounded-xl border border-amber-500/30 bg-amber-500/10 p-4"><p className="font-semibold text-amber-700 dark:text-amber-300">Supplier requested another schedule</p><p className="text-sm text-[var(--text-primary)]">{selected.alternative_schedule_message}</p>{!showScheduleForm && <button type="button" onClick={() => { setReplacing(true); setScheduleError(''); setDrafts([emptyDraft(), emptyDraft(), emptyDraft()]); }} className="mt-3 inline-flex min-h-11 items-center gap-2 rounded-xl bg-cyan-700 px-4 font-semibold text-white"><CalendarPlus className="h-4 w-4" />Provide New Meeting Options</button>}</div>}
        {selected.status === 'QUALIFIED_FOR_MEETING' && available.length > 0 && !replacing && <section aria-labelledby="published-options" className="mt-4 rounded-2xl border border-cyan-500/30 bg-cyan-500/5 p-4"><h4 id="published-options" className="text-xs font-bold uppercase tracking-wide text-cyan-700 dark:text-cyan-300">Meeting options published</h4><ol className="mt-3 grid gap-2 sm:grid-cols-3">{available.map((slot, index) => <li key={slot.id} className="rounded-xl border border-[var(--border-color)] bg-[var(--bg-card)] p-3"><p className="text-xs font-semibold text-[var(--text-muted)]">Option {index + 1}</p><p className="mt-1 text-sm font-semibold text-[var(--text-primary)]">{manilaDate(slotStart(slot))}</p><p className="text-sm text-[var(--text-secondary)]">{slotTimes(slot)}</p></li>)}</ol><p className="mt-3 text-sm text-[var(--text-primary)]"><span className="font-semibold">Status:</span> Waiting for supplier to select a schedule.</p></section>}
        {selected.status === 'QUALIFIED_FOR_MEETING' && available.length === 0 && !replacing && <p className="mt-4 rounded-xl border border-amber-500/30 bg-amber-500/10 p-3 text-sm text-[var(--text-primary)]">All published options have passed. Publish new meeting options.</p>}
        {showScheduleForm && <><p className="mt-4 text-sm text-[var(--text-secondary)]">{replacing ? 'New options replace the currently published ones.' : 'Publish at least three options, each on a different date.'}</p><div className="mt-3 space-y-3">{drafts.map((draft, index) => { const duplicate = duplicateDates.has(draft.date); return <fieldset key={index} className="rounded-2xl border border-[var(--border-color)] p-4"><legend className="px-1 font-semibold text-[var(--text-primary)]">Option {index + 1}</legend><div className="grid gap-3 sm:grid-cols-3">{([['date', 'Date', 'date'], ['start_time', 'Start Time', 'time'], ['end_time', 'End Time', 'time']] as const).map(([field, label, type]) => <label key={field} className="text-sm text-[var(--text-secondary)]">{label}<input type={type} value={draft[field]} aria-invalid={field === 'date' && duplicate ? true : undefined} onChange={(event) => { setScheduleError(''); setDrafts((current) => current.map((item, itemIndex) => itemIndex === index ? { ...item, [field]: event.target.value } : item)); }} className={`mt-1 min-h-11 w-full rounded-xl border bg-[var(--bg-input)] px-3 text-[var(--text-primary)] ${field === 'date' && duplicate ? 'border-rose-500' : 'border-[var(--border-color)]'}`} /></label>)}</div>{duplicate && <p className="mt-2 text-sm text-rose-700 dark:text-rose-300">This date is already used by another option.</p>}{drafts.length > 3 && <button type="button" onClick={() => setDrafts((current) => current.filter((_, itemIndex) => itemIndex !== index))} className="mt-2 min-h-11 px-3 text-sm text-rose-600">Remove option</button>}</fieldset>; })}</div>
        {scheduleError && <p role="alert" className="mt-3 rounded-xl border border-rose-500/30 bg-rose-500/10 p-3 text-sm text-rose-700 dark:text-rose-300">{scheduleError}</p>}
        <div className="mt-4 flex flex-col gap-3 sm:flex-row sm:justify-between"><div className="flex flex-col gap-3 sm:flex-row"><button type="button" onClick={() => setDrafts((current) => [...current, emptyDraft()])} className="inline-flex min-h-11 items-center justify-center gap-2 rounded-xl border border-[var(--border-color)] px-4 text-[var(--text-primary)]"><Plus className="h-4 w-4" />Add another option</button>{replacing && <button type="button" onClick={() => { setReplacing(false); setScheduleError(''); }} className="min-h-11 rounded-xl px-4 text-[var(--text-secondary)] hover:bg-[var(--bg-hover)]">Cancel</button>}</div><button type="button" disabled={saving} onClick={() => void publish()} className="inline-flex min-h-11 items-center justify-center gap-2 rounded-xl bg-cyan-700 px-4 font-semibold text-white disabled:opacity-50"><CalendarPlus className="h-4 w-4" />{saving ? 'Publishing…' : 'Publish Meeting Options'}</button></div></>}</>}
      {step === 'meeting' && !confirmed && <p className="rounded-xl border border-amber-500/30 bg-amber-500/10 p-4 text-sm text-[var(--text-primary)]">The confirmed meeting could not be loaded. Refresh the application.</p>}
      {step === 'meeting' && confirmed && <><h3 className="text-xl font-bold text-[var(--text-primary)]">Meeting</h3><div className="mt-4 rounded-2xl border border-violet-500/30 bg-violet-500/10 p-5"><p className="text-xs font-bold uppercase text-violet-700 dark:text-violet-300">Confirmed Schedule</p><p className="mt-2 text-lg font-semibold text-[var(--text-primary)]">{manilaDate(slotStart(confirmed))}</p><p className="text-base text-[var(--text-primary)]">{slotTimes(confirmed)}</p><p className="text-sm text-[var(--text-muted)]">Asia/Manila</p><p className="mt-3 text-sm text-[var(--text-secondary)]">Selected by supplier{confirmed.selected_at ? ` · Confirmed on ${manilaDate(confirmed.selected_at)}` : ''}</p></div><section aria-labelledby="meeting-status-heading" className={`mt-4 rounded-2xl border p-4 ${meetingEnded ? 'border-emerald-500/30 bg-emerald-500/10' : 'border-[var(--border-color)] bg-[var(--bg-input)]'}`}><h4 id="meeting-status-heading" className="text-xs font-bold uppercase tracking-wide text-[var(--text-muted)]">Meeting Status</h4><p className="mt-1 font-semibold text-[var(--text-primary)]">{meetingEnded ? 'Ready for Completion' : 'Scheduled'}</p><p id="meeting-completion-help" className="mt-1 text-sm text-[var(--text-secondary)]">{meetingEnded ? 'The scheduled meeting has ended. You may now complete the meeting evaluation.' : `Meeting completion will be available after ${manilaTime(slotEnd(confirmed))} on ${manilaDate(slotEnd(confirmed))} (Asia/Manila).`}</p></section>
        <section aria-labelledby="evaluation-heading" className="mt-5 rounded-2xl border border-[var(--border-color)] p-4 sm:p-5"><h4 id="evaluation-heading" className="font-bold text-[var(--text-primary)]">Internal Meeting Evaluation <span className="text-sm font-normal text-[var(--text-muted)]">(Admin only)</span></h4>
          <fieldset className="mt-3"><legend className="text-sm font-semibold text-[var(--text-primary)]">Meeting checklist</legend><div className="mt-2 grid gap-2 sm:grid-cols-2">{checklistItems.map(([key, label]) => <label key={key} className="flex min-h-11 cursor-pointer items-center gap-3 rounded-xl border border-[var(--border-color)] px-3 text-sm text-[var(--text-primary)]"><input type="checkbox" checked={evaluation[key]} onChange={(event) => setEvaluation((current) => ({ ...current, [key]: event.target.checked }))} className="h-5 w-5 shrink-0" />{label}</label>)}</div></fieldset>
          <fieldset className="mt-4" aria-describedby="assessment-help"><legend className="text-sm font-semibold text-[var(--text-primary)]">Overall Assessment <span aria-hidden="true" className="text-rose-600">*</span><span className="sr-only">(required)</span></legend><p id="assessment-help" className="text-xs text-[var(--text-muted)]">A recommendation for your records. The final approval or rejection is made in Step 4.</p><div className="mt-2 grid gap-2 sm:grid-cols-3">{(Object.keys(assessmentLabels) as Assessment[]).map((code) => <label key={code} className={`flex min-h-11 cursor-pointer items-center gap-3 rounded-xl border px-3 text-sm text-[var(--text-primary)] ${evaluation.overall_assessment === code ? 'border-cyan-500 bg-cyan-500/10' : 'border-[var(--border-color)]'}`}><input type="radio" name="overall-assessment" value={code} checked={evaluation.overall_assessment === code} onChange={() => setEvaluation((current) => ({ ...current, overall_assessment: code }))} className="h-4 w-4 shrink-0" />{assessmentLabels[code]}</label>)}</div></fieldset>
          <label className="mt-4 block text-sm font-semibold text-[var(--text-primary)]">Additional Notes <span className="font-normal text-[var(--text-muted)]">(optional)</span><textarea rows={4} maxLength={5000} value={evaluation.notes} onChange={(event) => setEvaluation((current) => ({ ...current, notes: event.target.value }))} className="mt-2 w-full rounded-xl border border-[var(--border-color)] bg-[var(--bg-input)] p-3 font-normal" /></label>
        </section>
        <div className="mt-4 flex flex-col items-stretch gap-2 sm:items-end"><button type="button" disabled={!canComplete} aria-describedby="complete-help" onClick={() => void complete(confirmed)} className="min-h-11 rounded-xl bg-indigo-700 px-4 font-semibold text-white disabled:cursor-not-allowed disabled:opacity-50">{saving ? 'Completing…' : 'Mark Meeting Completed'}</button><p id="complete-help" className="text-sm text-[var(--text-secondary)] sm:text-right">{!meetingEnded ? `Available after ${manilaTime(slotEnd(confirmed))} (Asia/Manila), when the scheduled meeting ends.` : !evaluation.overall_assessment ? 'Select an overall assessment to complete the meeting.' : 'The application will move to Step 4 — Final Decision.'}</p></div></>}
      {step === 'decision' && <><h3 className="text-xl font-bold text-[var(--text-primary)]">Final Supplier Decision</h3>{confirmed && <div className="mt-4 rounded-xl border border-[var(--border-color)] p-4"><p className="font-semibold text-[var(--text-primary)]">Meeting completed</p><p className="text-sm text-[var(--text-secondary)]">{manilaDate(slotStart(confirmed))} · {slotTimes(confirmed)} (Asia/Manila)</p>{confirmed.evaluation && <div className="mt-3"><p className="text-sm text-[var(--text-primary)]"><span className="font-semibold">Overall assessment:</span> {assessmentLabels[confirmed.evaluation.overall_assessment] ?? confirmed.evaluation.overall_assessment}</p><ul className="mt-2 grid gap-1 text-sm sm:grid-cols-2">{checklistItems.map(([key, label]) => <li key={key} className="text-[var(--text-secondary)]">{confirmed.evaluation?.[key] ? '✓ ' : '✗ '}{label}<span className="sr-only">{confirmed.evaluation?.[key] ? ' (yes)' : ' (no)'}</span></li>)}</ul></div>}{confirmed.evaluation_notes && <div className="mt-3"><p className="text-xs font-bold uppercase text-[var(--text-muted)]">{confirmed.evaluation ? 'Additional notes' : 'Meeting notes'}</p><p className="mt-1 whitespace-pre-wrap text-sm text-[var(--text-primary)]">{confirmed.evaluation_notes}</p></div>}</div>}{selected.status === 'MEETING_COMPLETED' && <div className="mt-5 flex gap-3 sm:justify-end"><button type="button" onClick={() => { setMode('reject'); setCodes([]); }} className="min-h-11 rounded-xl border border-rose-500 px-4 font-semibold text-rose-700 dark:text-rose-300">Reject Application</button><button type="button" onClick={() => setConfirmApproval(true)} className="min-h-11 rounded-xl bg-emerald-700 px-4 font-semibold text-white">Approve as Supplier</button></div>}{selected.status === 'APPROVED' && <><div className="mt-5 rounded-xl border border-emerald-500/30 bg-emerald-500/10 p-4 text-emerald-700 dark:text-emerald-300">Created active supplier: {selected.approved_supplier?.supplier_code} · {selected.approved_supplier?.name}</div><div className="mt-5"><OfferingList offerings={selected.offerings ?? []} approved /></div></>}{selected.status === 'REJECTED' && <div className="mt-5 rounded-xl border border-rose-500/30 bg-rose-500/10 p-4 text-[var(--text-primary)]">{selected.supplier_message}</div>}{mode === 'reject' && selected.status === 'MEETING_COMPLETED' && <ReasonForm title="Final Rejection" reasons={finalRejectReasons} codes={codes} toggle={toggle} supplierMessage={supplierMessage} setSupplierMessage={setSupplierMessage} internalNote={internalNote} setInternalNote={setInternalNote} cancel={resetForm} submit={() => void decide('reject')} saving={saving} destructive />}</>}
      {!!selected.events?.length && <section className="mt-7 border-t border-[var(--border-color)] pt-5"><h3 className="font-bold text-[var(--text-primary)]">Application history</h3><ol className="mt-3 space-y-3">{selected.events.map((event) => <li key={event.id} className="border-l-2 border-cyan-500/40 pl-3"><p className="text-sm font-semibold text-[var(--text-primary)]">{event.title}</p><p className="text-sm text-[var(--text-secondary)]">{event.description}</p><time className="text-xs text-[var(--text-muted)]">{manila(event.occurred_at)}</time></li>)}</ol></section>}
    </div></div>}
    {confirmApproval && selected && <div className="fixed inset-0 z-[70] flex items-center justify-center bg-slate-950/80 p-4" role="dialog" aria-modal="true" aria-labelledby="approval-title"><div className="max-w-md rounded-2xl bg-[var(--bg-card)] p-6"><h2 id="approval-title" className="text-xl font-bold text-[var(--text-primary)]">Approve as Supplier</h2><p className="mt-3 text-sm text-[var(--text-secondary)]">Approve “{selected.company_name}” as an official supplier? This creates one active Supplier record.</p><div className="mt-6 flex justify-end gap-3"><button type="button" onClick={() => setConfirmApproval(false)} className="min-h-11 rounded-xl border border-[var(--border-color)] px-4">Cancel</button><button type="button" disabled={saving} onClick={() => void approve()} className="min-h-11 rounded-xl bg-emerald-700 px-4 text-white"><Check className="mr-2 inline h-4 w-4" />Approve as Supplier</button></div></div></div>}
    {preview && <div className="fixed inset-0 z-[80] flex items-center justify-center bg-slate-950/85 p-4" role="dialog" aria-modal="true" onClick={() => setPreview(null)}><div className="max-h-[94vh] w-full max-w-5xl overflow-auto rounded-2xl bg-white p-4 dark:bg-[#0d1322]" onClick={(event) => event.stopPropagation()}><button type="button" onClick={() => setPreview(null)} className="float-right h-11 w-11" aria-label="Close preview"><X className="mx-auto h-5 w-5" /></button><h2 className="text-lg font-semibold">{preview.name}</h2><div className="clear-both pt-4">{preview.mime === 'application/pdf' ? <iframe src={preview.url} title={preview.name} className="h-[75vh] w-full" /> : <img src={preview.url} alt={preview.name} className="mx-auto max-h-[75vh] max-w-full" />}</div></div></div>}
  </section>;
}

type ReasonProps = { title: string; reasons: Reason[]; codes: string[]; toggle: (code: string) => void; supplierMessage: string; setSupplierMessage: (value: string) => void; internalNote: string; setInternalNote: (value: string) => void; cancel: () => void; submit: () => void; saving: boolean; destructive: boolean };
function OfferingList({ offerings, approved }: { offerings: Offering[]; approved: boolean }) {
  const pending = offerings.filter((offering) => offering.type === 'PRODUCT' && !offering.mapped_product).length;
  return <section aria-label="Products and services offered"><p className="mb-2 text-xs font-bold uppercase text-[var(--text-muted)]">Products / services offered</p>
    {offerings.length === 0 ? <p className="text-sm text-[var(--text-secondary)]">No structured offerings (submitted before structured offerings were introduced).</p> : <ul className="grid gap-2 sm:grid-cols-2">{offerings.map((offering) => <li key={offering.id} className="min-w-0 rounded-xl border border-[var(--border-color)] p-3"><p className="break-words text-sm font-semibold text-[var(--text-primary)]">{offering.name}</p><p className="text-xs text-[var(--text-secondary)]">{offering.type === 'PRODUCT' ? 'Product' : 'Service'}{offering.category ? ` · ${offering.category}` : ''}</p>{offering.description && <p className="mt-1 break-words text-xs text-[var(--text-secondary)]">{offering.description}</p>}{approved && offering.type === 'PRODUCT' && <p className={`mt-2 inline-flex rounded-full border px-2 py-0.5 text-xs font-semibold ${offering.mapped_product ? 'border-emerald-500/30 text-emerald-700 dark:text-emerald-300' : 'border-amber-500/30 text-amber-700 dark:text-amber-300'}`}>{offering.mapped_product ? `Mapped to ${offering.mapped_product.name}` : 'Pending catalog mapping'}</p>}</li>)}</ul>}
    {approved && pending > 0 && <p className="mt-2 text-sm text-[var(--text-secondary)]">{pending} product offering{pending === 1 ? '' : 's'} awaiting mapping in Product Catalog → Supplier Offerings.</p>}
  </section>;
}

function ReasonForm(props: ReasonProps) { return <section className="mt-5 rounded-2xl border border-[var(--border-color)] bg-[var(--bg-input)] p-5"><h3 className="text-lg font-bold text-[var(--text-primary)]">{props.title}</h3><fieldset className="mt-3"><legend className="text-sm font-semibold text-[var(--text-primary)]">Select all applicable reasons</legend><div className="mt-2 grid gap-2 sm:grid-cols-2">{props.reasons.map((reason) => <label key={reason.code} className="flex min-h-11 cursor-pointer gap-3 rounded-xl border border-[var(--border-color)] p-3 text-sm text-[var(--text-primary)]"><input type="checkbox" checked={props.codes.includes(reason.code)} onChange={() => props.toggle(reason.code)} className="mt-0.5 h-5 w-5" />{reason.label}</label>)}</div></fieldset><label className="mt-4 block text-sm font-semibold text-[var(--text-primary)]">Supplier-visible message<textarea rows={3} value={props.supplierMessage} onChange={(event) => props.setSupplierMessage(event.target.value)} className="mt-2 w-full rounded-xl border border-[var(--border-color)] bg-[var(--bg-card)] p-3" /></label><label className="mt-4 block text-sm font-semibold text-[var(--text-primary)]">Internal Admin note <span className="font-normal text-[var(--text-muted)]">(optional; never shown to supplier)</span><textarea rows={3} value={props.internalNote} onChange={(event) => props.setInternalNote(event.target.value)} className="mt-2 w-full rounded-xl border border-[var(--border-color)] bg-[var(--bg-card)] p-3" /></label><div className="mt-4 flex justify-end gap-3"><button type="button" onClick={props.cancel} className="min-h-11 rounded-xl border border-[var(--border-color)] px-4">Cancel</button><button type="button" disabled={props.saving || props.codes.length === 0 || props.supplierMessage.trim().length < 3} onClick={props.submit} className={`min-h-11 rounded-xl px-4 font-semibold text-white disabled:opacity-50 ${props.destructive ? 'bg-rose-700' : 'bg-amber-700'}`}>{props.title}</button></div></section>; }
