import React, { useCallback, useEffect, useState } from 'react';
import { Check, Download, Eye, FileText, Image as ImageIcon, RefreshCw, Search, X } from 'lucide-react';
import { apiClient } from '../../lib/api';

type AttachmentType = 'BUSINESS_CERTIFICATE' | 'BUSINESS_PERMIT' | 'PRODUCT_SERVICE_IMAGE';
type Attachment = { id: number; attachment_type: AttachmentType; original_name: string; mime_type: string; file_size: number; preview_url: string; download_url: string };
type Application = {
  id: number; application_number: string; company_name: string; address: string; contact_person: string;
  email: string; phone: string; business_type: string; supply_category: string; products_services: string;
  status: 'PENDING' | 'UNDER_REVIEW' | 'APPROVED' | 'REJECTED'; submitted_at: string; reviewed_at?: string;
  decision_reason?: string; reviewed_by?: { name: string }; approved_supplier?: { supplier_code: string; name: string };
  attachments?: Attachment[];
};
type Preview = { url: string; name: string; mimeType: string };

const statusStyle: Record<string, string> = { PENDING: 'border-amber-500/30 bg-amber-500/10 text-amber-600 dark:text-amber-300', UNDER_REVIEW: 'border-sky-500/30 bg-sky-500/10 text-sky-700 dark:text-sky-300', APPROVED: 'border-emerald-500/30 bg-emerald-500/10 text-emerald-700 dark:text-emerald-300', REJECTED: 'border-rose-500/30 bg-rose-500/10 text-rose-700 dark:text-rose-300' };
const formatFileSize = (bytes: number) => bytes < 1024 * 1024 ? `${Math.max(1, Math.round(bytes / 1024))} KB` : `${(bytes / (1024 * 1024)).toFixed(1)} MB`;

const SupplierApplicationsTab: React.FC = () => {
  const [items, setItems] = useState<Application[]>([]); const [selected, setSelected] = useState<Application | null>(null);
  const [search, setSearch] = useState(''); const [status, setStatus] = useState(''); const [pendingCount, setPendingCount] = useState(0);
  const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState(''); const [reason, setReason] = useState('');
  const [preview, setPreview] = useState<Preview | null>(null); const [fileAction, setFileAction] = useState<number | null>(null); const [imageThumbnails, setImageThumbnails] = useState<Record<number, string>>({});

  const load = useCallback(async () => { setLoading(true); try { const response = await apiClient.get('/admin/supplier-applications', { params: { search: search || undefined, status: status || undefined } }); setItems(response.data?.data || []); setPendingCount(response.data?.meta?.pending_action || 0); setError(''); } catch (e: any) { setError(e?.response?.data?.message || 'Unable to load supplier applications.'); } finally { setLoading(false); } }, [search, status]);
  useEffect(() => { const timer = window.setTimeout(() => void load(), 250); return () => window.clearTimeout(timer); }, [load]);
  useEffect(() => () => { if (preview?.url) URL.revokeObjectURL(preview.url); }, [preview]);
  useEffect(() => {
    let active = true; const thumbnailUrls: string[] = [];
    const images = selected?.attachments?.filter((attachment) => attachment.attachment_type === 'PRODUCT_SERVICE_IMAGE') || [];
    setImageThumbnails({});
    void Promise.all(images.map(async (attachment) => {
      try {
        const response = await apiClient.get(attachment.preview_url, { responseType: 'blob' });
        const url = URL.createObjectURL(response.data); thumbnailUrls.push(url);
        return [attachment.id, url] as const;
      } catch { return null; }
    })).then((entries) => {
      if (!active) { thumbnailUrls.forEach((url) => URL.revokeObjectURL(url)); return; }
      setImageThumbnails(Object.fromEntries(entries.filter((entry): entry is readonly [number, string] => entry !== null)));
    });
    return () => { active = false; thumbnailUrls.forEach((url) => URL.revokeObjectURL(url)); };
  }, [selected]);
  useEffect(() => {
    const onKeyDown = (event: KeyboardEvent) => { if (event.key === 'Escape') { if (preview) setPreview(null); else setSelected(null); } };
    if (selected || preview) document.addEventListener('keydown', onKeyDown);
    return () => document.removeEventListener('keydown', onKeyDown);
  }, [selected, preview]);

  const open = async (item: Application) => { setError(''); try { if (item.status === 'PENDING') await apiClient.post(`/admin/supplier-applications/${item.id}/review`); const response = await apiClient.get(`/admin/supplier-applications/${item.id}`); setSelected(response.data.data); setReason(''); await load(); } catch (e: any) { setError(e?.response?.data?.message || 'Unable to open the application.'); } };
  const decide = async (action: 'approve' | 'reject') => { if (!selected) return; setSaving(true); setError(''); try { const response = await apiClient.post(`/admin/supplier-applications/${selected.id}/${action}`, action === 'reject' ? { reason } : {}); setSelected(response.data.data); setReason(''); await load(); } catch (e: any) { const validation = e?.response?.data?.errors; setError(validation ? String(Object.values(validation).flat()[0]) : e?.response?.data?.message || `Unable to ${action} application.`); } finally { setSaving(false); } };
  const previewFile = async (attachment: Attachment) => { setFileAction(attachment.id); setError(''); try { const response = await apiClient.get(attachment.preview_url, { responseType: 'blob' }); setPreview({ url: URL.createObjectURL(response.data), name: attachment.original_name, mimeType: attachment.mime_type }); } catch (e: any) { setError(e?.response?.data?.message || 'Unable to preview this attachment.'); } finally { setFileAction(null); } };
  const downloadFile = async (attachment: Attachment) => { setFileAction(attachment.id); setError(''); try { const response = await apiClient.get(attachment.download_url, { responseType: 'blob' }); const url = URL.createObjectURL(response.data); const link = document.createElement('a'); link.href = url; link.download = attachment.original_name; document.body.appendChild(link); link.click(); link.remove(); window.setTimeout(() => URL.revokeObjectURL(url), 1000); } catch (e: any) { setError(e?.response?.data?.message || 'Unable to download this attachment.'); } finally { setFileAction(null); } };

  const attachmentFor = (type: AttachmentType) => selected?.attachments?.filter((attachment) => attachment.attachment_type === type) || [];
  const renderAttachment = (type: AttachmentType, label: string, missing: string, image = false) => {
    const attachments = attachmentFor(type);
    if (!attachments.length) return <div className="rounded-xl border border-dashed border-[var(--border-color)] p-4"><p className="text-sm font-semibold text-[var(--text-primary)]">{label}</p><p className="mt-1 text-sm text-[var(--text-muted)]">{missing}</p></div>;
    return <div><h4 className="mb-2 text-sm font-semibold text-[var(--text-primary)]">{label} <span className="font-normal text-[var(--text-muted)]">({attachments.length})</span></h4><div className={image ? 'grid gap-3 min-[430px]:grid-cols-2 lg:grid-cols-3' : 'space-y-3'}>{attachments.map((attachment, index) => <article key={attachment.id} className="min-w-0 rounded-xl border border-[var(--border-color)] bg-[var(--bg-input)] p-4">
      {image && imageThumbnails[attachment.id] && <img src={imageThumbnails[attachment.id]} alt={`Submitted ${label} ${index + 1}`} className="mb-3 h-28 w-full rounded-lg border border-[var(--border-color)] object-cover" />}
      <div className="flex items-start gap-3">{image ? <ImageIcon className="mt-0.5 h-5 w-5 shrink-0 text-cyan-600 dark:text-cyan-300" /> : <FileText className="mt-0.5 h-5 w-5 shrink-0 text-cyan-600 dark:text-cyan-300" />}<div className="min-w-0"><p className="text-sm font-semibold text-[var(--text-primary)]">{label}</p><p className="mt-0.5 break-all text-sm text-[var(--text-secondary)]">{attachment.original_name}</p><p className="mt-1 text-xs text-[var(--text-muted)]">{attachment.mime_type} · {formatFileSize(attachment.file_size)}</p></div></div>
      <div className="mt-3 flex flex-wrap gap-2"><button type="button" disabled={fileAction === attachment.id} onClick={() => void previewFile(attachment)} className="inline-flex min-h-11 cursor-pointer items-center gap-2 rounded-lg border border-cyan-600 px-3 text-sm font-semibold text-cyan-700 hover:bg-cyan-500/10 focus:outline-none focus:ring-2 focus:ring-cyan-500/40 disabled:cursor-wait disabled:opacity-60 dark:text-cyan-300"><Eye className="h-4 w-4" />Preview</button><button type="button" disabled={fileAction === attachment.id} onClick={() => void downloadFile(attachment)} className="inline-flex min-h-11 cursor-pointer items-center gap-2 rounded-lg border border-[var(--border-color)] px-3 text-sm font-semibold text-[var(--text-secondary)] hover:bg-[var(--bg-hover)] focus:outline-none focus:ring-2 focus:ring-cyan-500/40 disabled:cursor-wait disabled:opacity-60"><Download className="h-4 w-4" />Download</button></div>
    </article>)}</div></div>;
  };

  return <section className="mx-auto w-full max-w-7xl space-y-5 p-4 sm:p-6">
    <div className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><div className="flex items-center gap-2"><h1 className="text-2xl font-bold text-[var(--text-primary)]">Supplier applications</h1>{pendingCount > 0 && <span className="rounded-full bg-amber-500 px-2 py-0.5 text-xs font-bold text-slate-950">{pendingCount} pending</span>}</div><p className="mt-1 text-sm text-[var(--text-muted)]">Review applicants before creating official supplier records.</p></div><button type="button" onClick={() => void load()} disabled={loading} aria-label="Refresh applications" className="flex min-h-11 cursor-pointer items-center justify-center gap-2 rounded-xl border border-[var(--border-color)] px-4 text-sm text-[var(--text-secondary)] hover:bg-[var(--bg-hover)] focus:outline-none focus:ring-2 focus:ring-cyan-500/40"><RefreshCw className={`h-4 w-4 ${loading ? 'animate-spin' : ''}`} />Refresh</button></div>
    {error && <div role="alert" className="rounded-xl border border-rose-500/30 bg-rose-500/10 px-4 py-3 text-sm text-rose-600 dark:text-rose-300">{error}</div>}
    <div className="grid gap-3 rounded-2xl border border-[var(--border-color)] bg-[var(--bg-card)] p-4 sm:grid-cols-[1fr_210px]"><label className="relative"><span className="sr-only">Search applications</span><Search className="absolute left-3 top-3.5 h-4 w-4 text-[var(--text-muted)]" /><input value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Search reference, company, contact, or email" className="min-h-11 w-full rounded-xl border border-[var(--border-color)] bg-[var(--bg-input)] pl-10 pr-3 text-sm text-[var(--text-primary)] outline-none focus:ring-2 focus:ring-cyan-500/40" /></label><label><span className="sr-only">Filter by status</span><select value={status} onChange={(e) => setStatus(e.target.value)} className="min-h-11 w-full cursor-pointer rounded-xl border border-[var(--border-color)] bg-[var(--bg-input)] px-3 text-sm text-[var(--text-primary)] outline-none focus:ring-2 focus:ring-cyan-500/40"><option value="">All statuses</option><option value="PENDING">Pending</option><option value="UNDER_REVIEW">Under review</option><option value="APPROVED">Approved</option><option value="REJECTED">Rejected</option></select></label></div>
    <div className="overflow-hidden rounded-2xl border border-[var(--border-color)] bg-[var(--bg-card)]"><div className="overflow-x-auto"><table className="w-full min-w-[820px]"><thead className="bg-[var(--bg-hover)] text-left text-xs uppercase tracking-wider text-[var(--text-muted)]"><tr><th className="px-4 py-3">Reference / date</th><th className="px-4 py-3">Company</th><th className="px-4 py-3">Contact</th><th className="px-4 py-3">Category</th><th className="px-4 py-3">Status</th><th className="px-4 py-3 text-right">Action</th></tr></thead><tbody className="divide-y divide-[var(--border-color)]">{items.map((item) => <tr key={item.id} className="text-sm"><td className="px-4 py-4"><p className="font-mono font-semibold text-[var(--text-primary)]">{item.application_number}</p><p className="mt-1 text-xs text-[var(--text-muted)]">{new Date(item.submitted_at).toLocaleString()}</p></td><td className="px-4 py-4"><p className="font-semibold text-[var(--text-primary)]">{item.company_name}</p><p className="text-xs text-[var(--text-muted)]">{item.business_type}</p></td><td className="px-4 py-4 text-[var(--text-secondary)]"><p>{item.contact_person}</p><p className="text-xs">{item.email}</p></td><td className="px-4 py-4 text-[var(--text-secondary)]">{item.supply_category}</td><td className="px-4 py-4"><span className={`rounded-full border px-2.5 py-1 text-xs font-semibold ${statusStyle[item.status]}`}>{item.status.replace('_', ' ')}</span></td><td className="px-4 py-4 text-right"><button type="button" onClick={() => void open(item)} className="inline-flex min-h-11 cursor-pointer items-center gap-2 rounded-lg px-3 text-sm font-semibold text-cyan-700 hover:bg-cyan-500/10 focus:outline-none focus:ring-2 focus:ring-cyan-500/40 dark:text-cyan-300"><Eye className="h-4 w-4" />Review</button></td></tr>)}{!loading && items.length === 0 && <tr><td colSpan={6} className="px-4 py-12 text-center text-sm text-[var(--text-muted)]">No applications match these filters.</td></tr>}</tbody></table></div></div>
    {selected && <div className="fixed inset-0 z-50 flex items-end justify-center bg-slate-950/70 p-0 backdrop-blur-sm sm:items-center sm:p-6" role="dialog" aria-modal="true" aria-labelledby="application-review-title"><div className="max-h-[95vh] w-full max-w-3xl overflow-y-auto overscroll-contain rounded-t-3xl border border-[var(--border-color)] bg-[var(--bg-card)] p-5 shadow-2xl sm:rounded-3xl sm:p-7"><div className="sticky -top-5 z-10 -mx-1 flex items-start justify-between gap-4 bg-[var(--bg-card)] px-1 pb-4 pt-1 sm:-top-7 sm:pt-1"><div><p className="font-mono text-xs font-semibold text-cyan-700 dark:text-cyan-300">{selected.application_number}</p><h2 id="application-review-title" className="mt-1 text-2xl font-bold text-[var(--text-primary)]">{selected.company_name}</h2></div><button type="button" onClick={() => setSelected(null)} aria-label="Close application review" className="flex h-11 w-11 shrink-0 cursor-pointer items-center justify-center rounded-xl hover:bg-[var(--bg-hover)] focus:outline-none focus:ring-2 focus:ring-cyan-500/40"><X className="h-5 w-5" /></button></div>
      <div className="mt-2 grid gap-4 sm:grid-cols-2">{[['Status', selected.status.replace('_', ' ')], ['Business type', selected.business_type], ['Supply category', selected.supply_category], ['Contact', `${selected.contact_person} · ${selected.email} · ${selected.phone}`], ['Address', selected.address]].map(([label, value], index) => <div key={label} className={index === 4 ? 'sm:col-span-2' : ''}><p className="text-xs font-bold uppercase tracking-wider text-[var(--text-muted)]">{label}</p><p className="mt-1 whitespace-pre-wrap break-words text-sm leading-6 text-[var(--text-primary)]">{value}</p></div>)}</div>
      <section aria-labelledby="review-business-documents" className="mt-7 border-t border-[var(--border-color)] pt-5"><h3 id="review-business-documents" className="text-xs font-bold uppercase tracking-wider text-[var(--text-muted)]">Business documents</h3><div className="mt-3 grid gap-3 sm:grid-cols-2">{renderAttachment('BUSINESS_CERTIFICATE', 'Business Certificate', 'No certificate attached.')}{renderAttachment('BUSINESS_PERMIT', 'Business Permit', 'No business permit attached.')}</div></section>
      <section aria-labelledby="review-products-services" className="mt-7 border-t border-[var(--border-color)] pt-5"><h3 id="review-products-services" className="text-xs font-bold uppercase tracking-wider text-[var(--text-muted)]">Products / services</h3><p className="mt-2 whitespace-pre-wrap break-words text-sm leading-6 text-[var(--text-primary)]">{selected.products_services}</p><h3 className="mt-5 text-xs font-bold uppercase tracking-wider text-[var(--text-muted)]">Product / Service Images</h3><div className="mt-3">{renderAttachment('PRODUCT_SERVICE_IMAGE', 'Product / Service Images', 'No product/service images attached.', true)}</div></section>
      {selected.approved_supplier && <div className="mt-6 rounded-xl border border-emerald-500/30 bg-emerald-500/10 p-4 text-sm text-emerald-700 dark:text-emerald-300">Created supplier: {selected.approved_supplier.supplier_code} · {selected.approved_supplier.name}</div>}{selected.decision_reason && <div className="mt-6 rounded-xl border border-rose-500/30 bg-rose-500/10 p-4"><p className="text-xs font-bold uppercase text-rose-600 dark:text-rose-300">Rejection reason</p><p className="mt-1 text-sm text-[var(--text-primary)]">{selected.decision_reason}</p></div>}
      {['PENDING', 'UNDER_REVIEW'].includes(selected.status) && <div className="mt-7 border-t border-[var(--border-color)] pt-5"><label htmlFor="rejection-reason" className="text-sm font-semibold text-[var(--text-primary)]">Rejection reason <span className="font-normal text-[var(--text-muted)]">(required only for reject)</span></label><textarea id="rejection-reason" rows={3} value={reason} onChange={(e) => setReason(e.target.value)} maxLength={2000} className="mt-2 w-full rounded-xl border border-[var(--border-color)] bg-[var(--bg-input)] p-3 text-sm text-[var(--text-primary)] outline-none focus:ring-2 focus:ring-cyan-500/40" /><div className="mt-4 flex flex-col-reverse gap-3 sm:flex-row sm:justify-end"><button type="button" disabled={saving || reason.trim().length < 3} onClick={() => void decide('reject')} className="inline-flex min-h-11 cursor-pointer items-center justify-center gap-2 rounded-xl border border-rose-500 px-4 font-semibold text-rose-600 hover:bg-rose-500/10 disabled:cursor-not-allowed disabled:opacity-50 dark:text-rose-300"><X className="h-4 w-4" />Reject</button><button type="button" disabled={saving} onClick={() => void decide('approve')} className="inline-flex min-h-11 cursor-pointer items-center justify-center gap-2 rounded-xl bg-emerald-700 px-4 font-semibold text-white hover:bg-emerald-800 disabled:cursor-not-allowed disabled:opacity-50"><Check className="h-4 w-4" />{saving ? 'Processing…' : 'Approve and create supplier'}</button></div></div>}
    </div></div>}
    {preview && <div className="fixed inset-0 z-[60] flex items-center justify-center bg-slate-950/85 p-3 sm:p-6" role="dialog" aria-modal="true" aria-labelledby="attachment-preview-title" onClick={() => setPreview(null)}><div className="flex max-h-[94vh] w-full max-w-5xl flex-col overflow-hidden rounded-2xl bg-white shadow-2xl dark:bg-[#0d1322]" onClick={(event) => event.stopPropagation()}><div className="flex items-center justify-between gap-3 border-b border-slate-200 p-4 dark:border-slate-700"><div className="min-w-0"><h2 id="attachment-preview-title" className="text-lg font-semibold text-slate-950 dark:text-slate-100">Attachment preview</h2><p className="truncate text-sm text-slate-600 dark:text-slate-400" title={preview.name}>{preview.name}</p></div><button type="button" autoFocus onClick={() => setPreview(null)} aria-label="Close attachment preview" className="flex h-11 w-11 shrink-0 cursor-pointer items-center justify-center rounded-lg text-slate-900 hover:bg-slate-100 focus:outline-none focus:ring-2 focus:ring-cyan-500/40 dark:text-slate-100 dark:hover:bg-slate-800"><X className="h-5 w-5" /></button></div><div className="min-h-0 flex-1 overflow-auto bg-slate-100 p-3 dark:bg-slate-950">{preview.mimeType === 'application/pdf' ? <iframe src={preview.url} title={`Preview of ${preview.name}`} className="h-[75vh] w-full rounded-lg bg-white" /> : <img src={preview.url} alt={`Preview of ${preview.name}`} className="mx-auto max-h-[75vh] max-w-full rounded-lg object-contain" />}</div></div></div>}
  </section>;
};

export default SupplierApplicationsTab;
